/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdcButton {
        /**
          * @default 'button'
         */
        "buttonType": 'button' | 'submit' | 'reset';
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface AdcContainer {
        /**
          * @default '1200px'
         */
        "maxWidth": string;
        /**
          * @default '20px'
         */
        "padding": string;
    }
    interface AdcHeader {
        "headerTitle": string;
        "subtitle"?: string;
    }
    interface AdcStatCard {
        "cardTitle": string;
        /**
          * @default '#0066cc'
         */
        "color": string;
        "description"?: string;
        "value": string | number;
    }
}
export interface AdcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcButtonElement;
}
declare global {
    interface HTMLAdcButtonElementEventMap {
        "adcClick": MouseEvent;
    }
    interface HTMLAdcButtonElement extends Components.AdcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcButtonElement: {
        prototype: HTMLAdcButtonElement;
        new (): HTMLAdcButtonElement;
    };
    interface HTMLAdcContainerElement extends Components.AdcContainer, HTMLStencilElement {
    }
    var HTMLAdcContainerElement: {
        prototype: HTMLAdcContainerElement;
        new (): HTMLAdcContainerElement;
    };
    interface HTMLAdcHeaderElement extends Components.AdcHeader, HTMLStencilElement {
    }
    var HTMLAdcHeaderElement: {
        prototype: HTMLAdcHeaderElement;
        new (): HTMLAdcHeaderElement;
    };
    interface HTMLAdcStatCardElement extends Components.AdcStatCard, HTMLStencilElement {
    }
    var HTMLAdcStatCardElement: {
        prototype: HTMLAdcStatCardElement;
        new (): HTMLAdcStatCardElement;
    };
    interface HTMLElementTagNameMap {
        "adc-button": HTMLAdcButtonElement;
        "adc-container": HTMLAdcContainerElement;
        "adc-header": HTMLAdcHeaderElement;
        "adc-stat-card": HTMLAdcStatCardElement;
    }
}
declare namespace LocalJSX {
    interface AdcButton {
        /**
          * @default 'button'
         */
        "buttonType"?: 'button' | 'submit' | 'reset';
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onAdcClick"?: (event: AdcButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface AdcContainer {
        /**
          * @default '1200px'
         */
        "maxWidth"?: string;
        /**
          * @default '20px'
         */
        "padding"?: string;
    }
    interface AdcHeader {
        "headerTitle": string;
        "subtitle"?: string;
    }
    interface AdcStatCard {
        "cardTitle": string;
        /**
          * @default '#0066cc'
         */
        "color"?: string;
        "description"?: string;
        "value": string | number;
    }
    interface IntrinsicElements {
        "adc-button": AdcButton;
        "adc-container": AdcContainer;
        "adc-header": AdcHeader;
        "adc-stat-card": AdcStatCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "adc-button": LocalJSX.AdcButton & JSXBase.HTMLAttributes<HTMLAdcButtonElement>;
            "adc-container": LocalJSX.AdcContainer & JSXBase.HTMLAttributes<HTMLAdcContainerElement>;
            "adc-header": LocalJSX.AdcHeader & JSXBase.HTMLAttributes<HTMLAdcHeaderElement>;
            "adc-stat-card": LocalJSX.AdcStatCard & JSXBase.HTMLAttributes<HTMLAdcStatCardElement>;
        }
    }
}
