/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * ADC Button - Componente de botón con Tailwind CSS
     * Usa clases de Tailwind via CSS personalizado con
     * @apply para mantener el encapsulamiento del Shadow DOM
     */
    interface AdcButton {
        /**
          * @default "button"
         */
        "buttonType": "button" | "submit" | "reset";
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "md"
         */
        "size": "sm" | "md" | "lg";
        /**
          * @default "primary"
         */
        "variant": "primary" | "secondary" | "success" | "warning" | "danger";
    }
    interface AdcContainer {
        /**
          * @default "1200px"
         */
        "maxWidth": string;
        /**
          * @default "20px"
         */
        "padding": string;
    }
    /**
     * Componente de error centrado para mostrar cuando una aplicación falla
     */
    interface AdcError {
        /**
          * Color del icono y borde (por defecto #ef4444 - rojo)
          * @default "#ef4444"
         */
        "color": string;
        /**
          * Descripción personalizada del error
         */
        "errorDescription"?: string;
        /**
          * Título personalizado del error
         */
        "errorTitle"?: string;
        /**
          * Código de error HTTP (ej: 404, 500, 503)
         */
        "httpError"?: number;
    }
    interface AdcHeader {
        "headerTitle": string;
        "subtitle"?: string;
    }
    /**
     * ADC Stat Card - Componente de tarjeta de estadísticas con Tailwind CSS
     * Usa clases de Tailwind via CSS personalizado con
     * @apply 
     */
    interface AdcStatCard {
        "cardTitle": string;
        /**
          * @default "primary"
         */
        "color": "primary" | "success" | "warning" | "danger" | "default";
        "description"?: string;
        "value": string | number;
    }
}
export interface AdcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcButtonElement;
}
declare global {
    interface HTMLAdcButtonElementEventMap {
        "adcClick": any;
    }
    /**
     * ADC Button - Componente de botón con Tailwind CSS
     * Usa clases de Tailwind via CSS personalizado con
     * @apply para mantener el encapsulamiento del Shadow DOM
     */
    interface HTMLAdcButtonElement extends Components.AdcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcButtonElement: {
        prototype: HTMLAdcButtonElement;
        new (): HTMLAdcButtonElement;
    };
    interface HTMLAdcContainerElement extends Components.AdcContainer, HTMLStencilElement {
    }
    var HTMLAdcContainerElement: {
        prototype: HTMLAdcContainerElement;
        new (): HTMLAdcContainerElement;
    };
    /**
     * Componente de error centrado para mostrar cuando una aplicación falla
     */
    interface HTMLAdcErrorElement extends Components.AdcError, HTMLStencilElement {
    }
    var HTMLAdcErrorElement: {
        prototype: HTMLAdcErrorElement;
        new (): HTMLAdcErrorElement;
    };
    interface HTMLAdcHeaderElement extends Components.AdcHeader, HTMLStencilElement {
    }
    var HTMLAdcHeaderElement: {
        prototype: HTMLAdcHeaderElement;
        new (): HTMLAdcHeaderElement;
    };
    /**
     * ADC Stat Card - Componente de tarjeta de estadísticas con Tailwind CSS
     * Usa clases de Tailwind via CSS personalizado con
     * @apply 
     */
    interface HTMLAdcStatCardElement extends Components.AdcStatCard, HTMLStencilElement {
    }
    var HTMLAdcStatCardElement: {
        prototype: HTMLAdcStatCardElement;
        new (): HTMLAdcStatCardElement;
    };
    interface HTMLElementTagNameMap {
        "adc-button": HTMLAdcButtonElement;
        "adc-container": HTMLAdcContainerElement;
        "adc-error": HTMLAdcErrorElement;
        "adc-header": HTMLAdcHeaderElement;
        "adc-stat-card": HTMLAdcStatCardElement;
    }
}
declare namespace LocalJSX {
    /**
     * ADC Button - Componente de botón con Tailwind CSS
     * Usa clases de Tailwind via CSS personalizado con
     * @apply para mantener el encapsulamiento del Shadow DOM
     */
    interface AdcButton {
        /**
          * @default "button"
         */
        "buttonType"?: "button" | "submit" | "reset";
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onAdcClick"?: (event: AdcButtonCustomEvent<any>) => void;
        /**
          * @default "md"
         */
        "size"?: "sm" | "md" | "lg";
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "secondary" | "success" | "warning" | "danger";
    }
    interface AdcContainer {
        /**
          * @default "1200px"
         */
        "maxWidth"?: string;
        /**
          * @default "20px"
         */
        "padding"?: string;
    }
    /**
     * Componente de error centrado para mostrar cuando una aplicación falla
     */
    interface AdcError {
        /**
          * Color del icono y borde (por defecto #ef4444 - rojo)
          * @default "#ef4444"
         */
        "color"?: string;
        /**
          * Descripción personalizada del error
         */
        "errorDescription"?: string;
        /**
          * Título personalizado del error
         */
        "errorTitle"?: string;
        /**
          * Código de error HTTP (ej: 404, 500, 503)
         */
        "httpError"?: number;
    }
    interface AdcHeader {
        "headerTitle": string;
        "subtitle"?: string;
    }
    /**
     * ADC Stat Card - Componente de tarjeta de estadísticas con Tailwind CSS
     * Usa clases de Tailwind via CSS personalizado con
     * @apply 
     */
    interface AdcStatCard {
        "cardTitle": string;
        /**
          * @default "primary"
         */
        "color"?: "primary" | "success" | "warning" | "danger" | "default";
        "description"?: string;
        "value": string | number;
    }
    interface IntrinsicElements {
        "adc-button": AdcButton;
        "adc-container": AdcContainer;
        "adc-error": AdcError;
        "adc-header": AdcHeader;
        "adc-stat-card": AdcStatCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * ADC Button - Componente de botón con Tailwind CSS
             * Usa clases de Tailwind via CSS personalizado con
             * @apply para mantener el encapsulamiento del Shadow DOM
             */
            "adc-button": LocalJSX.AdcButton & JSXBase.HTMLAttributes<HTMLAdcButtonElement>;
            "adc-container": LocalJSX.AdcContainer & JSXBase.HTMLAttributes<HTMLAdcContainerElement>;
            /**
             * Componente de error centrado para mostrar cuando una aplicación falla
             */
            "adc-error": LocalJSX.AdcError & JSXBase.HTMLAttributes<HTMLAdcErrorElement>;
            "adc-header": LocalJSX.AdcHeader & JSXBase.HTMLAttributes<HTMLAdcHeaderElement>;
            /**
             * ADC Stat Card - Componente de tarjeta de estadísticas con Tailwind CSS
             * Usa clases de Tailwind via CSS personalizado con
             * @apply 
             */
            "adc-stat-card": LocalJSX.AdcStatCard & JSXBase.HTMLAttributes<HTMLAdcStatCardElement>;
        }
    }
}
