/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdcButton {
        /**
          * @default "button"
         */
        "buttonType": "button" | "submit" | "reset";
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "primary"
         */
        "variant": "primary" | "secondary";
    }
    interface AdcContainer {
        /**
          * @default "100%"
         */
        "maxWidth": string;
        /**
          * @default "16px"
         */
        "padding": string;
    }
    interface AdcHeader {
        "headerTitle": string;
        "subtitle"?: string;
    }
    interface AdcStatCard {
        "cardTitle": string;
        /**
          * @default "#805ad5"
         */
        "color": string;
        "description"?: string;
        "value": string | number;
    }
}
export interface AdcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcButtonElement;
}
declare global {
    interface HTMLAdcButtonElementEventMap {
        "adcClick": any;
    }
    interface HTMLAdcButtonElement extends Components.AdcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcButtonElement: {
        prototype: HTMLAdcButtonElement;
        new (): HTMLAdcButtonElement;
    };
    interface HTMLAdcContainerElement extends Components.AdcContainer, HTMLStencilElement {
    }
    var HTMLAdcContainerElement: {
        prototype: HTMLAdcContainerElement;
        new (): HTMLAdcContainerElement;
    };
    interface HTMLAdcHeaderElement extends Components.AdcHeader, HTMLStencilElement {
    }
    var HTMLAdcHeaderElement: {
        prototype: HTMLAdcHeaderElement;
        new (): HTMLAdcHeaderElement;
    };
    interface HTMLAdcStatCardElement extends Components.AdcStatCard, HTMLStencilElement {
    }
    var HTMLAdcStatCardElement: {
        prototype: HTMLAdcStatCardElement;
        new (): HTMLAdcStatCardElement;
    };
    interface HTMLElementTagNameMap {
        "adc-button": HTMLAdcButtonElement;
        "adc-container": HTMLAdcContainerElement;
        "adc-header": HTMLAdcHeaderElement;
        "adc-stat-card": HTMLAdcStatCardElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface AdcButton {
        /**
          * @default "button"
         */
        "buttonType"?: "button" | "submit" | "reset";
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onAdcClick"?: (event: AdcButtonCustomEvent<any>) => void;
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "secondary";
    }
    interface AdcContainer {
        /**
          * @default "100%"
         */
        "maxWidth"?: string;
        /**
          * @default "16px"
         */
        "padding"?: string;
    }
    interface AdcHeader {
        "headerTitle": string;
        "subtitle"?: string;
    }
    interface AdcStatCard {
        "cardTitle": string;
        /**
          * @default "#805ad5"
         */
        "color"?: string;
        "description"?: string;
        "value": string | number;
    }

    interface AdcButtonAttributes {
        "disabled": boolean;
        "buttonType": "button" | "submit" | "reset";
        "variant": "primary" | "secondary";
    }
    interface AdcContainerAttributes {
        "maxWidth": string;
        "padding": string;
    }
    interface AdcHeaderAttributes {
        "headerTitle": string;
        "subtitle": string;
    }
    interface AdcStatCardAttributes {
        "cardTitle": string;
        "value": string;
        "description": string;
        "color": string;
    }

    interface IntrinsicElements {
        "adc-button": Omit<AdcButton, keyof AdcButtonAttributes> & { [K in keyof AdcButton & keyof AdcButtonAttributes]?: AdcButton[K] } & { [K in keyof AdcButton & keyof AdcButtonAttributes as `attr:${K}`]?: AdcButtonAttributes[K] } & { [K in keyof AdcButton & keyof AdcButtonAttributes as `prop:${K}`]?: AdcButton[K] };
        "adc-container": Omit<AdcContainer, keyof AdcContainerAttributes> & { [K in keyof AdcContainer & keyof AdcContainerAttributes]?: AdcContainer[K] } & { [K in keyof AdcContainer & keyof AdcContainerAttributes as `attr:${K}`]?: AdcContainerAttributes[K] } & { [K in keyof AdcContainer & keyof AdcContainerAttributes as `prop:${K}`]?: AdcContainer[K] };
        "adc-header": Omit<AdcHeader, keyof AdcHeaderAttributes> & { [K in keyof AdcHeader & keyof AdcHeaderAttributes]?: AdcHeader[K] } & { [K in keyof AdcHeader & keyof AdcHeaderAttributes as `attr:${K}`]?: AdcHeaderAttributes[K] } & { [K in keyof AdcHeader & keyof AdcHeaderAttributes as `prop:${K}`]?: AdcHeader[K] } & OneOf<"headerTitle", AdcHeader["headerTitle"], AdcHeaderAttributes["headerTitle"]>;
        "adc-stat-card": Omit<AdcStatCard, keyof AdcStatCardAttributes> & { [K in keyof AdcStatCard & keyof AdcStatCardAttributes]?: AdcStatCard[K] } & { [K in keyof AdcStatCard & keyof AdcStatCardAttributes as `attr:${K}`]?: AdcStatCardAttributes[K] } & { [K in keyof AdcStatCard & keyof AdcStatCardAttributes as `prop:${K}`]?: AdcStatCard[K] } & OneOf<"cardTitle", AdcStatCard["cardTitle"], AdcStatCardAttributes["cardTitle"]> & OneOf<"value", AdcStatCard["value"], AdcStatCardAttributes["value"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "adc-button": LocalJSX.IntrinsicElements["adc-button"] & JSXBase.HTMLAttributes<HTMLAdcButtonElement>;
            "adc-container": LocalJSX.IntrinsicElements["adc-container"] & JSXBase.HTMLAttributes<HTMLAdcContainerElement>;
            "adc-header": LocalJSX.IntrinsicElements["adc-header"] & JSXBase.HTMLAttributes<HTMLAdcHeaderElement>;
            "adc-stat-card": LocalJSX.IntrinsicElements["adc-stat-card"] & JSXBase.HTMLAttributes<HTMLAdcStatCardElement>;
        }
    }
}
