/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AccessMenuItem } from "./components/molecules/adc-access-button/adc-access-button";
import { Block } from "./components/organisms/adc-blocks-renderer/adc-blocks-renderer";
import { DropdownMenuItem } from "./components/molecules/adc-dropdown-menu/adc-dropdown-menu";
import { InlineToken } from "./components/atoms/adc-inline-tokens/adc-inline-tokens";
import { SelectOption } from "./components/atoms/adc-select/adc-select";
import { AccessMenuItem as AccessMenuItem1 } from "./components/molecules/adc-access-button/adc-access-button.js";
import { TabItem } from "./components/atoms/adc-tabs/adc-tabs";
export { AccessMenuItem } from "./components/molecules/adc-access-button/adc-access-button";
export { Block } from "./components/organisms/adc-blocks-renderer/adc-blocks-renderer";
export { DropdownMenuItem } from "./components/molecules/adc-dropdown-menu/adc-dropdown-menu";
export { InlineToken } from "./components/atoms/adc-inline-tokens/adc-inline-tokens";
export { SelectOption } from "./components/atoms/adc-select/adc-select";
export { AccessMenuItem as AccessMenuItem1 } from "./components/molecules/adc-access-button/adc-access-button.js";
export { TabItem } from "./components/atoms/adc-tabs/adc-tabs";
export namespace Components {
    /**
     * Botón de acceso que muestra:
     * - Si logueado: avatar + dropdown con menú de items + logout
     * - Si no logueado: botón "Ingresar" que redirige a auth
     */
    interface AdcAccessButton {
        /**
          * URL base de la API (en dev: http://localhost:3000, en prod: vacío para usar relativo)
          * @default ["localhost", "127.0.0.1"].includes(globalThis.location?.hostname) 		? `${globalThis.location?.protocol}//${globalThis.location?.hostname}:3000` 		: ""
         */
        "apiBaseUrl": string;
        /**
          * URL base del auth (en dev: localhost:3012, en prod: auth.adigitalcafe.com)
          * @default `${globalThis.location?.protocol}//auth.adigitalcafe.com${globalThis.location?.port ? `:${globalThis.location?.port}` : ""}`
         */
        "authUrl": string;
        /**
          * Texto del botón cuando no está logueado
          * @default "Ingresar"
         */
        "loginText": string;
        /**
          * URL de logout
          * @default "/api/auth/logout"
         */
        "logoutApiUrl": string;
        /**
          * Texto del botón de logout
          * @default "Cerrar sesión"
         */
        "logoutText": string;
        /**
          * Items del menú dropdown (array de {label, href, icon?})
          * @default []
         */
        "menuItems": AccessMenuItem[];
        /**
          * URL de la API de sesión
          * @default "/api/auth/session"
         */
        "sessionApiUrl": string;
    }
    interface AdcAppsMenu {
        /**
          * Override default apps list (JSON array of AppMenuItem)
         */
        "apps"?: string;
    }
    interface AdcBadge {
        /**
          * Badge color
          * @default "gray"
         */
        "color": "gray" | "red" | "orange" | "yellow" | "green" | "teal" | "blue" | "purple" | "pink";
        /**
          * Whether to show a dot indicator
          * @default false
         */
        "dot": boolean;
        /**
          * Badge size
          * @default "md"
         */
        "size": "sm" | "md";
    }
    interface AdcBlocksRenderer {
        /**
          * @default []
         */
        "blocks": Block[];
    }
    /**
     * Panel con efecto glassmorphism/blur
     * Ideal para formularios de auth, modales y tarjetas destacadas
     */
    interface AdcBlurPanel {
        /**
          * Intensidad del blur (sm, md, lg, xl)
          * @default "lg"
         */
        "blur": "sm" | "md" | "lg" | "xl";
        /**
          * Mostrar borde luminoso sutil
          * @default false
         */
        "glow": boolean;
        /**
          * Padding interno (none, sm, md, lg, xl)
          * @default "lg"
         */
        "padding": "none" | "sm" | "md" | "lg" | "xl";
        /**
          * Radio de borde (sm, md, lg, xl, full)
          * @default "xl"
         */
        "radius": "sm" | "md" | "lg" | "xl" | "full";
        /**
          * Variante de estilo - default: fondo semi-transparente estándar - elevated: más opaco con sombra pronunciada - subtle: casi transparente, solo blur
          * @default "default"
         */
        "variant": "default" | "elevated" | "subtle";
    }
    interface AdcButton {
        "ariaLabel"?: string;
        "disabled"?: boolean;
        "href"?: string;
        /**
          * Label text - when provided, takes precedence over slot content for dynamic updates
         */
        "label"?: string;
        /**
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
        /**
          * @default "primary"
         */
        "variant": "primary" | "accent";
    }
    interface AdcButtonRounded {
        "ariaLabel"?: string;
        "href"?: string;
        /**
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
        /**
          * Visual variant
          * @default "default"
         */
        "variant": "default" | "danger";
    }
    interface AdcCallout {
        /**
          * @default "note"
         */
        "role": "note" | "status" | "alert";
        /**
          * @default "info"
         */
        "tone": "info" | "warning" | "success" | "error";
    }
    interface AdcCodeBlock {
        "ariaLabel"?: string;
        /**
          * @default ""
         */
        "content": string;
        "language"?: string;
    }
    interface AdcContentCard {
        "bannerAlt"?: string;
        "bannerUrl"?: string;
        /**
          * @default false
         */
        "compact": boolean;
        "description"?: string;
        "href"?: string;
        /**
          * @default ""
         */
        "title": string;
    }
    interface AdcCustomError {
        /**
          * Auto-dismiss timeout in ms (only for toast variant). 0 = no auto-dismiss
          * @default 5000
         */
        "dismissTimeout": number;
        /**
          * If true, catches all errors not handled by specific key handlers
          * @default false
         */
        "global": boolean;
        /**
          * If true, listens for unhandled promise rejections
          * @default false
         */
        "handleUnhandled": boolean;
        /**
          * JSON array of error keys to handle. If empty and not global, shows warning.
         */
        "keys"?: string;
        /**
          * Maximum number of stacked toasts
          * @default 5
         */
        "maxStack": number;
        /**
          * Display variant: callout (inline) or toast (floating notification)
          * @default "toast"
         */
        "variant": "callout" | "toast";
    }
    interface AdcDivider {
    }
    interface AdcDropdownMenu {
        /**
          * @default "left"
         */
        "alignState": "left" | "right";
        /**
          * @default []
         */
        "items": DropdownMenuItem[];
        /**
          * @default true
         */
        "openOnHover": boolean;
    }
    interface AdcFeatureCard {
        /**
          * @default true
         */
        "staticRender": boolean;
        /**
          * @default ""
         */
        "title": string;
    }
    interface AdcIconAppCommunity {
        /**
          * @default "1.75rem"
         */
        "size": string;
    }
    interface AdcIconAppIdentity {
        /**
          * @default "1.75rem"
         */
        "size": string;
    }
    interface AdcIconCommunity {
        /**
          * @default "2rem"
         */
        "size": string;
    }
    interface AdcIconLearning {
        /**
          * @default "2rem"
         */
        "size": string;
    }
    interface AdcIconLeftArrow {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcIconLogout {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcIconNitro {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcIconOpensource {
        /**
          * @default "2rem"
         */
        "size": string;
    }
    interface AdcIconPencil {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcIconVip {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcInlineTokens {
        /**
          * @default ""
         */
        "fallback": string;
        /**
          * @default []
         */
        "tokens": InlineToken[];
    }
    interface AdcInput {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "inputId"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default "text"
         */
        "type"?: string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface AdcLayout {
        "apiBaseUrl"?: string;
        "authUrl"?: string;
        /**
          * @default "Abby's Digital Cafe"
         */
        "brandName": string;
        /**
          * @default "Una taza de código con tintes de amistad"
         */
        "brandSlogan": string;
        /**
          * @default "https://abbytec.dev.ar/"
         */
        "creatorHref": string;
        /**
          * @default "Abbytec"
         */
        "creatorName": string;
        /**
          * @default "/"
         */
        "homeHref": string;
        /**
          * @default "ADC"
         */
        "logoAlt": string;
        /**
          * @default "/ui/images/mini-logo.webp"
         */
        "logoSrc": string;
        /**
          * @default true
         */
        "showAccessButton": boolean;
    }
    interface AdcListBlock {
        "ariaLabel"?: string;
        /**
          * @default []
         */
        "items": string[];
        /**
          * @default false
         */
        "ordered": boolean;
        "start"?: number;
    }
    interface AdcLpBadge {
        "as"?: "button" | "span";
        /**
          * @default ""
         */
        "color": string;
        "slug"?: string;
        /**
          * @default ""
         */
        "title": string;
    }
    interface AdcModal {
        /**
          * Whether clicking the backdrop closes the modal
          * @default true
         */
        "dismissOnBackdrop": boolean;
        /**
          * Whether pressing Escape closes the modal
          * @default true
         */
        "dismissOnEscape": boolean;
        /**
          * Modal title
          * @default ""
         */
        "modalTitle": string;
        /**
          * Whether the modal is visible
          * @default false
         */
        "open": boolean;
        /**
          * Size variant
          * @default "md"
         */
        "size": "sm" | "md" | "lg";
    }
    interface AdcPagination {
        /**
          * Current page (1-indexed)
          * @default 1
         */
        "currentPage": number;
        /**
          * Max visible page buttons
          * @default 5
         */
        "maxVisible": number;
        /**
          * Total number of pages
          * @default 1
         */
        "totalPages": number;
    }
    interface AdcQuote {
        /**
          * @default true
         */
        "staticRender": boolean;
    }
    interface AdcSearchInput {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * @default 300
         */
        "debounce": number;
        /**
          * @default ""
         */
        "inputId"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        /**
          * @default ""
         */
        "placeholder": string;
        /**
          * @default "text"
         */
        "type"?: string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface AdcSelect {
        /**
          * @default []
         */
        "options": SelectOption[];
        /**
          * @default "Seleccione"
         */
        "placeholder": string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface AdcShareButtons {
        /**
          * @default ""
         */
        "description": string;
        /**
          * @default ""
         */
        "title": string;
        /**
          * @default ""
         */
        "url": string;
    }
    interface AdcSiteFooter {
        /**
          * @default ""
         */
        "brandName": string;
        /**
          * @default ""
         */
        "brandSlogan": string;
        /**
          * @default ""
         */
        "creatorHref": string;
        /**
          * @default ""
         */
        "creatorName": string;
        /**
          * @default false
         */
        "lowerSign": boolean;
        /**
          * @default false
         */
        "registered": boolean;
    }
    interface AdcSiteHeader {
        /**
          * URL base de la API (en dev: http://localhost:3000, en prod: vacío)
          * @default ["localhost", "127.0.0.1"].includes(globalThis.location?.hostname) 		? `${globalThis.location?.protocol}//${globalThis.location?.hostname}:3000` 		: ""
         */
        "apiBaseUrl": string;
        /**
          * URL base para auth (dev vs prod)
          * @default `${globalThis.location?.protocol}//auth.adigitalcafe.com${globalThis.location?.port ? `:${globalThis.location?.port}` : ""}`
         */
        "authUrl": string;
        /**
          * @default "/"
         */
        "homeHref": string;
        /**
          * @default ""
         */
        "logoAlt": string;
        /**
          * @default ""
         */
        "logoSrc": string;
        /**
          * Mostrar botón de acceso/perfil
          * @default true
         */
        "showAccessButton": boolean;
        /**
          * Items del menú de usuario (array de {label, href, icon?})
          * @default []
         */
        "userMenuItems": AccessMenuItem1[];
    }
    /**
     * Skeleton loader component for placeholder content while loading
     * @example <adc-skeleton variant="text" />
     * <adc-skeleton variant="circular" width="48px" height="48px" />
     * <adc-skeleton variant="rectangular" height="200px" />
     * <adc-skeleton variant="button" />
     * <adc-skeleton variant="input" />
     */
    interface AdcSkeleton {
        /**
          * Animation type
          * @default "pulse"
         */
        "animation": "pulse" | "wave" | "none";
        /**
          * Custom height (CSS value). Defaults vary by variant
         */
        "height"?: string;
        /**
          * Number of lines for text variant
          * @default 1
         */
        "lines": number;
        /**
          * Border radius override
         */
        "rounded"?: string;
        /**
          * Variant determines the shape of the skeleton
          * @default "text"
         */
        "variant": "text" | "circular" | "rectangular" | "button" | "input";
        /**
          * Custom width (CSS value). Defaults vary by variant
         */
        "width"?: string;
    }
    interface AdcStarRating {
        "average"?: number | null;
        /**
          * @default false
         */
        "canRate": boolean;
        "count"?: number | null;
        "myRating"?: number | null;
        /**
          * @default false
         */
        "pending": boolean;
    }
    interface AdcTableBlock {
        "caption"?: string;
        "columnAlign"?: Array<"left" | "center" | "right">;
        /**
          * @default []
         */
        "header": string[];
        /**
          * @default false
         */
        "rowHeaders": boolean;
        /**
          * @default []
         */
        "rows": string[][];
    }
    interface AdcTabs {
        /**
          * Currently active tab ID
          * @default ""
         */
        "activeTab": string;
        /**
          * Tab items to display
          * @default []
         */
        "tabs": TabItem[] | string;
        /**
          * Visual variant
          * @default "underline"
         */
        "variant": "underline" | "pills";
    }
    interface AdcTestimonialCard {
        /**
          * @default ""
         */
        "author": string;
        /**
          * @default true
         */
        "staticRender": boolean;
    }
    interface AdcText {
        /**
          * @default true
         */
        "contain": boolean;
        /**
          * @default true
         */
        "staticRender": boolean;
    }
    interface AdcToggle {
        /**
          * Accessible name
         */
        "ariaLabel"?: string;
        /**
          * Whether the toggle is checked
          * @default false
         */
        "checked": boolean;
        /**
          * Whether the toggle is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Label text
         */
        "label"?: string;
    }
    interface AdcToggleBadge {
        /**
          * Whether the badge is in the active/selected state
          * @default false
         */
        "active": boolean;
    }
    /**
     * Componente YouTube Facade para carga perezosa de videos
     * Muestra una thumbnail clickeable en lugar de cargar el iframe inmediatamente
     * Mejora performance al evitar cargar el player de YouTube hasta que sea necesario
     */
    interface AdcYoutubeFacade {
        /**
          * Alto del contenedor (opcional, por defecto responsive 16:9)
         */
        "height"?: string;
        /**
          * URL o ID del video de YouTube (acepta URL completa o solo el ID)
         */
        "src": string;
        /**
          * Título del video para accesibilidad
          * @default "Video de YouTube"
         */
        "title": string;
        /**
          * Ancho del contenedor (opcional, por defecto responsive)
         */
        "width"?: string;
    }
}
export interface AdcAccessButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcAccessButtonElement;
}
export interface AdcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcButtonElement;
}
export interface AdcButtonRoundedCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcButtonRoundedElement;
}
export interface AdcContentCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcContentCardElement;
}
export interface AdcDropdownMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcDropdownMenuElement;
}
export interface AdcLpBadgeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcLpBadgeElement;
}
export interface AdcModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcModalElement;
}
export interface AdcPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcPaginationElement;
}
export interface AdcSearchInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcSearchInputElement;
}
export interface AdcSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcSelectElement;
}
export interface AdcStarRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcStarRatingElement;
}
export interface AdcTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcTabsElement;
}
export interface AdcToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcToggleElement;
}
export interface AdcToggleBadgeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcToggleBadgeElement;
}
declare global {
    interface HTMLAdcAccessButtonElementEventMap {
        "adcLogout": void;
        "adcLoginClick": void;
    }
    /**
     * Botón de acceso que muestra:
     * - Si logueado: avatar + dropdown con menú de items + logout
     * - Si no logueado: botón "Ingresar" que redirige a auth
     */
    interface HTMLAdcAccessButtonElement extends Components.AdcAccessButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcAccessButtonElementEventMap>(type: K, listener: (this: HTMLAdcAccessButtonElement, ev: AdcAccessButtonCustomEvent<HTMLAdcAccessButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcAccessButtonElementEventMap>(type: K, listener: (this: HTMLAdcAccessButtonElement, ev: AdcAccessButtonCustomEvent<HTMLAdcAccessButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcAccessButtonElement: {
        prototype: HTMLAdcAccessButtonElement;
        new (): HTMLAdcAccessButtonElement;
    };
    interface HTMLAdcAppsMenuElement extends Components.AdcAppsMenu, HTMLStencilElement {
    }
    var HTMLAdcAppsMenuElement: {
        prototype: HTMLAdcAppsMenuElement;
        new (): HTMLAdcAppsMenuElement;
    };
    interface HTMLAdcBadgeElement extends Components.AdcBadge, HTMLStencilElement {
    }
    var HTMLAdcBadgeElement: {
        prototype: HTMLAdcBadgeElement;
        new (): HTMLAdcBadgeElement;
    };
    interface HTMLAdcBlocksRendererElement extends Components.AdcBlocksRenderer, HTMLStencilElement {
    }
    var HTMLAdcBlocksRendererElement: {
        prototype: HTMLAdcBlocksRendererElement;
        new (): HTMLAdcBlocksRendererElement;
    };
    /**
     * Panel con efecto glassmorphism/blur
     * Ideal para formularios de auth, modales y tarjetas destacadas
     */
    interface HTMLAdcBlurPanelElement extends Components.AdcBlurPanel, HTMLStencilElement {
    }
    var HTMLAdcBlurPanelElement: {
        prototype: HTMLAdcBlurPanelElement;
        new (): HTMLAdcBlurPanelElement;
    };
    interface HTMLAdcButtonElementEventMap {
        "adcClick": MouseEvent;
    }
    interface HTMLAdcButtonElement extends Components.AdcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcButtonElement: {
        prototype: HTMLAdcButtonElement;
        new (): HTMLAdcButtonElement;
    };
    interface HTMLAdcButtonRoundedElementEventMap {
        "adcClick": MouseEvent;
    }
    interface HTMLAdcButtonRoundedElement extends Components.AdcButtonRounded, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcButtonRoundedElementEventMap>(type: K, listener: (this: HTMLAdcButtonRoundedElement, ev: AdcButtonRoundedCustomEvent<HTMLAdcButtonRoundedElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcButtonRoundedElementEventMap>(type: K, listener: (this: HTMLAdcButtonRoundedElement, ev: AdcButtonRoundedCustomEvent<HTMLAdcButtonRoundedElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcButtonRoundedElement: {
        prototype: HTMLAdcButtonRoundedElement;
        new (): HTMLAdcButtonRoundedElement;
    };
    interface HTMLAdcCalloutElement extends Components.AdcCallout, HTMLStencilElement {
    }
    var HTMLAdcCalloutElement: {
        prototype: HTMLAdcCalloutElement;
        new (): HTMLAdcCalloutElement;
    };
    interface HTMLAdcCodeBlockElement extends Components.AdcCodeBlock, HTMLStencilElement {
    }
    var HTMLAdcCodeBlockElement: {
        prototype: HTMLAdcCodeBlockElement;
        new (): HTMLAdcCodeBlockElement;
    };
    interface HTMLAdcContentCardElementEventMap {
        "cardClick": MouseEvent;
    }
    interface HTMLAdcContentCardElement extends Components.AdcContentCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcContentCardElementEventMap>(type: K, listener: (this: HTMLAdcContentCardElement, ev: AdcContentCardCustomEvent<HTMLAdcContentCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcContentCardElementEventMap>(type: K, listener: (this: HTMLAdcContentCardElement, ev: AdcContentCardCustomEvent<HTMLAdcContentCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcContentCardElement: {
        prototype: HTMLAdcContentCardElement;
        new (): HTMLAdcContentCardElement;
    };
    interface HTMLAdcCustomErrorElement extends Components.AdcCustomError, HTMLStencilElement {
    }
    var HTMLAdcCustomErrorElement: {
        prototype: HTMLAdcCustomErrorElement;
        new (): HTMLAdcCustomErrorElement;
    };
    interface HTMLAdcDividerElement extends Components.AdcDivider, HTMLStencilElement {
    }
    var HTMLAdcDividerElement: {
        prototype: HTMLAdcDividerElement;
        new (): HTMLAdcDividerElement;
    };
    interface HTMLAdcDropdownMenuElementEventMap {
        "adcItemClick": DropdownMenuItem;
    }
    interface HTMLAdcDropdownMenuElement extends Components.AdcDropdownMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcDropdownMenuElementEventMap>(type: K, listener: (this: HTMLAdcDropdownMenuElement, ev: AdcDropdownMenuCustomEvent<HTMLAdcDropdownMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcDropdownMenuElementEventMap>(type: K, listener: (this: HTMLAdcDropdownMenuElement, ev: AdcDropdownMenuCustomEvent<HTMLAdcDropdownMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcDropdownMenuElement: {
        prototype: HTMLAdcDropdownMenuElement;
        new (): HTMLAdcDropdownMenuElement;
    };
    interface HTMLAdcFeatureCardElement extends Components.AdcFeatureCard, HTMLStencilElement {
    }
    var HTMLAdcFeatureCardElement: {
        prototype: HTMLAdcFeatureCardElement;
        new (): HTMLAdcFeatureCardElement;
    };
    interface HTMLAdcIconAppCommunityElement extends Components.AdcIconAppCommunity, HTMLStencilElement {
    }
    var HTMLAdcIconAppCommunityElement: {
        prototype: HTMLAdcIconAppCommunityElement;
        new (): HTMLAdcIconAppCommunityElement;
    };
    interface HTMLAdcIconAppIdentityElement extends Components.AdcIconAppIdentity, HTMLStencilElement {
    }
    var HTMLAdcIconAppIdentityElement: {
        prototype: HTMLAdcIconAppIdentityElement;
        new (): HTMLAdcIconAppIdentityElement;
    };
    interface HTMLAdcIconCommunityElement extends Components.AdcIconCommunity, HTMLStencilElement {
    }
    var HTMLAdcIconCommunityElement: {
        prototype: HTMLAdcIconCommunityElement;
        new (): HTMLAdcIconCommunityElement;
    };
    interface HTMLAdcIconLearningElement extends Components.AdcIconLearning, HTMLStencilElement {
    }
    var HTMLAdcIconLearningElement: {
        prototype: HTMLAdcIconLearningElement;
        new (): HTMLAdcIconLearningElement;
    };
    interface HTMLAdcIconLeftArrowElement extends Components.AdcIconLeftArrow, HTMLStencilElement {
    }
    var HTMLAdcIconLeftArrowElement: {
        prototype: HTMLAdcIconLeftArrowElement;
        new (): HTMLAdcIconLeftArrowElement;
    };
    interface HTMLAdcIconLogoutElement extends Components.AdcIconLogout, HTMLStencilElement {
    }
    var HTMLAdcIconLogoutElement: {
        prototype: HTMLAdcIconLogoutElement;
        new (): HTMLAdcIconLogoutElement;
    };
    interface HTMLAdcIconNitroElement extends Components.AdcIconNitro, HTMLStencilElement {
    }
    var HTMLAdcIconNitroElement: {
        prototype: HTMLAdcIconNitroElement;
        new (): HTMLAdcIconNitroElement;
    };
    interface HTMLAdcIconOpensourceElement extends Components.AdcIconOpensource, HTMLStencilElement {
    }
    var HTMLAdcIconOpensourceElement: {
        prototype: HTMLAdcIconOpensourceElement;
        new (): HTMLAdcIconOpensourceElement;
    };
    interface HTMLAdcIconPencilElement extends Components.AdcIconPencil, HTMLStencilElement {
    }
    var HTMLAdcIconPencilElement: {
        prototype: HTMLAdcIconPencilElement;
        new (): HTMLAdcIconPencilElement;
    };
    interface HTMLAdcIconVipElement extends Components.AdcIconVip, HTMLStencilElement {
    }
    var HTMLAdcIconVipElement: {
        prototype: HTMLAdcIconVipElement;
        new (): HTMLAdcIconVipElement;
    };
    interface HTMLAdcInlineTokensElement extends Components.AdcInlineTokens, HTMLStencilElement {
    }
    var HTMLAdcInlineTokensElement: {
        prototype: HTMLAdcInlineTokensElement;
        new (): HTMLAdcInlineTokensElement;
    };
    interface HTMLAdcInputElement extends Components.AdcInput, HTMLStencilElement {
    }
    var HTMLAdcInputElement: {
        prototype: HTMLAdcInputElement;
        new (): HTMLAdcInputElement;
    };
    interface HTMLAdcLayoutElement extends Components.AdcLayout, HTMLStencilElement {
    }
    var HTMLAdcLayoutElement: {
        prototype: HTMLAdcLayoutElement;
        new (): HTMLAdcLayoutElement;
    };
    interface HTMLAdcListBlockElement extends Components.AdcListBlock, HTMLStencilElement {
    }
    var HTMLAdcListBlockElement: {
        prototype: HTMLAdcListBlockElement;
        new (): HTMLAdcListBlockElement;
    };
    interface HTMLAdcLpBadgeElementEventMap {
        "adcClick": void;
    }
    interface HTMLAdcLpBadgeElement extends Components.AdcLpBadge, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcLpBadgeElementEventMap>(type: K, listener: (this: HTMLAdcLpBadgeElement, ev: AdcLpBadgeCustomEvent<HTMLAdcLpBadgeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcLpBadgeElementEventMap>(type: K, listener: (this: HTMLAdcLpBadgeElement, ev: AdcLpBadgeCustomEvent<HTMLAdcLpBadgeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcLpBadgeElement: {
        prototype: HTMLAdcLpBadgeElement;
        new (): HTMLAdcLpBadgeElement;
    };
    interface HTMLAdcModalElementEventMap {
        "adcClose": void;
    }
    interface HTMLAdcModalElement extends Components.AdcModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcModalElementEventMap>(type: K, listener: (this: HTMLAdcModalElement, ev: AdcModalCustomEvent<HTMLAdcModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcModalElementEventMap>(type: K, listener: (this: HTMLAdcModalElement, ev: AdcModalCustomEvent<HTMLAdcModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcModalElement: {
        prototype: HTMLAdcModalElement;
        new (): HTMLAdcModalElement;
    };
    interface HTMLAdcPaginationElementEventMap {
        "adcPageChange": number;
    }
    interface HTMLAdcPaginationElement extends Components.AdcPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcPaginationElementEventMap>(type: K, listener: (this: HTMLAdcPaginationElement, ev: AdcPaginationCustomEvent<HTMLAdcPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcPaginationElementEventMap>(type: K, listener: (this: HTMLAdcPaginationElement, ev: AdcPaginationCustomEvent<HTMLAdcPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcPaginationElement: {
        prototype: HTMLAdcPaginationElement;
        new (): HTMLAdcPaginationElement;
    };
    interface HTMLAdcQuoteElement extends Components.AdcQuote, HTMLStencilElement {
    }
    var HTMLAdcQuoteElement: {
        prototype: HTMLAdcQuoteElement;
        new (): HTMLAdcQuoteElement;
    };
    interface HTMLAdcSearchInputElementEventMap {
        "adcInput": string;
    }
    interface HTMLAdcSearchInputElement extends Components.AdcSearchInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcSearchInputElementEventMap>(type: K, listener: (this: HTMLAdcSearchInputElement, ev: AdcSearchInputCustomEvent<HTMLAdcSearchInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcSearchInputElementEventMap>(type: K, listener: (this: HTMLAdcSearchInputElement, ev: AdcSearchInputCustomEvent<HTMLAdcSearchInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcSearchInputElement: {
        prototype: HTMLAdcSearchInputElement;
        new (): HTMLAdcSearchInputElement;
    };
    interface HTMLAdcSelectElementEventMap {
        "adcChange": string;
    }
    interface HTMLAdcSelectElement extends Components.AdcSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcSelectElementEventMap>(type: K, listener: (this: HTMLAdcSelectElement, ev: AdcSelectCustomEvent<HTMLAdcSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcSelectElementEventMap>(type: K, listener: (this: HTMLAdcSelectElement, ev: AdcSelectCustomEvent<HTMLAdcSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcSelectElement: {
        prototype: HTMLAdcSelectElement;
        new (): HTMLAdcSelectElement;
    };
    interface HTMLAdcShareButtonsElement extends Components.AdcShareButtons, HTMLStencilElement {
    }
    var HTMLAdcShareButtonsElement: {
        prototype: HTMLAdcShareButtonsElement;
        new (): HTMLAdcShareButtonsElement;
    };
    interface HTMLAdcSiteFooterElement extends Components.AdcSiteFooter, HTMLStencilElement {
    }
    var HTMLAdcSiteFooterElement: {
        prototype: HTMLAdcSiteFooterElement;
        new (): HTMLAdcSiteFooterElement;
    };
    interface HTMLAdcSiteHeaderElement extends Components.AdcSiteHeader, HTMLStencilElement {
    }
    var HTMLAdcSiteHeaderElement: {
        prototype: HTMLAdcSiteHeaderElement;
        new (): HTMLAdcSiteHeaderElement;
    };
    /**
     * Skeleton loader component for placeholder content while loading
     * @example <adc-skeleton variant="text" />
     * <adc-skeleton variant="circular" width="48px" height="48px" />
     * <adc-skeleton variant="rectangular" height="200px" />
     * <adc-skeleton variant="button" />
     * <adc-skeleton variant="input" />
     */
    interface HTMLAdcSkeletonElement extends Components.AdcSkeleton, HTMLStencilElement {
    }
    var HTMLAdcSkeletonElement: {
        prototype: HTMLAdcSkeletonElement;
        new (): HTMLAdcSkeletonElement;
    };
    interface HTMLAdcStarRatingElementEventMap {
        "adcRate": number;
    }
    interface HTMLAdcStarRatingElement extends Components.AdcStarRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcStarRatingElementEventMap>(type: K, listener: (this: HTMLAdcStarRatingElement, ev: AdcStarRatingCustomEvent<HTMLAdcStarRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcStarRatingElementEventMap>(type: K, listener: (this: HTMLAdcStarRatingElement, ev: AdcStarRatingCustomEvent<HTMLAdcStarRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcStarRatingElement: {
        prototype: HTMLAdcStarRatingElement;
        new (): HTMLAdcStarRatingElement;
    };
    interface HTMLAdcTableBlockElement extends Components.AdcTableBlock, HTMLStencilElement {
    }
    var HTMLAdcTableBlockElement: {
        prototype: HTMLAdcTableBlockElement;
        new (): HTMLAdcTableBlockElement;
    };
    interface HTMLAdcTabsElementEventMap {
        "adcTabChange": string;
    }
    interface HTMLAdcTabsElement extends Components.AdcTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcTabsElementEventMap>(type: K, listener: (this: HTMLAdcTabsElement, ev: AdcTabsCustomEvent<HTMLAdcTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcTabsElementEventMap>(type: K, listener: (this: HTMLAdcTabsElement, ev: AdcTabsCustomEvent<HTMLAdcTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcTabsElement: {
        prototype: HTMLAdcTabsElement;
        new (): HTMLAdcTabsElement;
    };
    interface HTMLAdcTestimonialCardElement extends Components.AdcTestimonialCard, HTMLStencilElement {
    }
    var HTMLAdcTestimonialCardElement: {
        prototype: HTMLAdcTestimonialCardElement;
        new (): HTMLAdcTestimonialCardElement;
    };
    interface HTMLAdcTextElement extends Components.AdcText, HTMLStencilElement {
    }
    var HTMLAdcTextElement: {
        prototype: HTMLAdcTextElement;
        new (): HTMLAdcTextElement;
    };
    interface HTMLAdcToggleElementEventMap {
        "adcChange": boolean;
    }
    interface HTMLAdcToggleElement extends Components.AdcToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcToggleElementEventMap>(type: K, listener: (this: HTMLAdcToggleElement, ev: AdcToggleCustomEvent<HTMLAdcToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcToggleElementEventMap>(type: K, listener: (this: HTMLAdcToggleElement, ev: AdcToggleCustomEvent<HTMLAdcToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcToggleElement: {
        prototype: HTMLAdcToggleElement;
        new (): HTMLAdcToggleElement;
    };
    interface HTMLAdcToggleBadgeElementEventMap {
        "adcToggle": void;
    }
    interface HTMLAdcToggleBadgeElement extends Components.AdcToggleBadge, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcToggleBadgeElementEventMap>(type: K, listener: (this: HTMLAdcToggleBadgeElement, ev: AdcToggleBadgeCustomEvent<HTMLAdcToggleBadgeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcToggleBadgeElementEventMap>(type: K, listener: (this: HTMLAdcToggleBadgeElement, ev: AdcToggleBadgeCustomEvent<HTMLAdcToggleBadgeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcToggleBadgeElement: {
        prototype: HTMLAdcToggleBadgeElement;
        new (): HTMLAdcToggleBadgeElement;
    };
    /**
     * Componente YouTube Facade para carga perezosa de videos
     * Muestra una thumbnail clickeable en lugar de cargar el iframe inmediatamente
     * Mejora performance al evitar cargar el player de YouTube hasta que sea necesario
     */
    interface HTMLAdcYoutubeFacadeElement extends Components.AdcYoutubeFacade, HTMLStencilElement {
    }
    var HTMLAdcYoutubeFacadeElement: {
        prototype: HTMLAdcYoutubeFacadeElement;
        new (): HTMLAdcYoutubeFacadeElement;
    };
    interface HTMLElementTagNameMap {
        "adc-access-button": HTMLAdcAccessButtonElement;
        "adc-apps-menu": HTMLAdcAppsMenuElement;
        "adc-badge": HTMLAdcBadgeElement;
        "adc-blocks-renderer": HTMLAdcBlocksRendererElement;
        "adc-blur-panel": HTMLAdcBlurPanelElement;
        "adc-button": HTMLAdcButtonElement;
        "adc-button-rounded": HTMLAdcButtonRoundedElement;
        "adc-callout": HTMLAdcCalloutElement;
        "adc-code-block": HTMLAdcCodeBlockElement;
        "adc-content-card": HTMLAdcContentCardElement;
        "adc-custom-error": HTMLAdcCustomErrorElement;
        "adc-divider": HTMLAdcDividerElement;
        "adc-dropdown-menu": HTMLAdcDropdownMenuElement;
        "adc-feature-card": HTMLAdcFeatureCardElement;
        "adc-icon-app-community": HTMLAdcIconAppCommunityElement;
        "adc-icon-app-identity": HTMLAdcIconAppIdentityElement;
        "adc-icon-community": HTMLAdcIconCommunityElement;
        "adc-icon-learning": HTMLAdcIconLearningElement;
        "adc-icon-left-arrow": HTMLAdcIconLeftArrowElement;
        "adc-icon-logout": HTMLAdcIconLogoutElement;
        "adc-icon-nitro": HTMLAdcIconNitroElement;
        "adc-icon-opensource": HTMLAdcIconOpensourceElement;
        "adc-icon-pencil": HTMLAdcIconPencilElement;
        "adc-icon-vip": HTMLAdcIconVipElement;
        "adc-inline-tokens": HTMLAdcInlineTokensElement;
        "adc-input": HTMLAdcInputElement;
        "adc-layout": HTMLAdcLayoutElement;
        "adc-list-block": HTMLAdcListBlockElement;
        "adc-lp-badge": HTMLAdcLpBadgeElement;
        "adc-modal": HTMLAdcModalElement;
        "adc-pagination": HTMLAdcPaginationElement;
        "adc-quote": HTMLAdcQuoteElement;
        "adc-search-input": HTMLAdcSearchInputElement;
        "adc-select": HTMLAdcSelectElement;
        "adc-share-buttons": HTMLAdcShareButtonsElement;
        "adc-site-footer": HTMLAdcSiteFooterElement;
        "adc-site-header": HTMLAdcSiteHeaderElement;
        "adc-skeleton": HTMLAdcSkeletonElement;
        "adc-star-rating": HTMLAdcStarRatingElement;
        "adc-table-block": HTMLAdcTableBlockElement;
        "adc-tabs": HTMLAdcTabsElement;
        "adc-testimonial-card": HTMLAdcTestimonialCardElement;
        "adc-text": HTMLAdcTextElement;
        "adc-toggle": HTMLAdcToggleElement;
        "adc-toggle-badge": HTMLAdcToggleBadgeElement;
        "adc-youtube-facade": HTMLAdcYoutubeFacadeElement;
    }
}
declare namespace LocalJSX {
    /**
     * Botón de acceso que muestra:
     * - Si logueado: avatar + dropdown con menú de items + logout
     * - Si no logueado: botón "Ingresar" que redirige a auth
     */
    interface AdcAccessButton {
        /**
          * URL base de la API (en dev: http://localhost:3000, en prod: vacío para usar relativo)
          * @default ["localhost", "127.0.0.1"].includes(globalThis.location?.hostname) 		? `${globalThis.location?.protocol}//${globalThis.location?.hostname}:3000` 		: ""
         */
        "apiBaseUrl"?: string;
        /**
          * URL base del auth (en dev: localhost:3012, en prod: auth.adigitalcafe.com)
          * @default `${globalThis.location?.protocol}//auth.adigitalcafe.com${globalThis.location?.port ? `:${globalThis.location?.port}` : ""}`
         */
        "authUrl"?: string;
        /**
          * Texto del botón cuando no está logueado
          * @default "Ingresar"
         */
        "loginText"?: string;
        /**
          * URL de logout
          * @default "/api/auth/logout"
         */
        "logoutApiUrl"?: string;
        /**
          * Texto del botón de logout
          * @default "Cerrar sesión"
         */
        "logoutText"?: string;
        /**
          * Items del menú dropdown (array de {label, href, icon?})
          * @default []
         */
        "menuItems"?: AccessMenuItem[];
        /**
          * Evento emitido al hacer login
         */
        "onAdcLoginClick"?: (event: AdcAccessButtonCustomEvent<void>) => void;
        /**
          * Evento emitido al cerrar sesión
         */
        "onAdcLogout"?: (event: AdcAccessButtonCustomEvent<void>) => void;
        /**
          * URL de la API de sesión
          * @default "/api/auth/session"
         */
        "sessionApiUrl"?: string;
    }
    interface AdcAppsMenu {
        /**
          * Override default apps list (JSON array of AppMenuItem)
         */
        "apps"?: string;
    }
    interface AdcBadge {
        /**
          * Badge color
          * @default "gray"
         */
        "color"?: "gray" | "red" | "orange" | "yellow" | "green" | "teal" | "blue" | "purple" | "pink";
        /**
          * Whether to show a dot indicator
          * @default false
         */
        "dot"?: boolean;
        /**
          * Badge size
          * @default "md"
         */
        "size"?: "sm" | "md";
    }
    interface AdcBlocksRenderer {
        /**
          * @default []
         */
        "blocks"?: Block[];
    }
    /**
     * Panel con efecto glassmorphism/blur
     * Ideal para formularios de auth, modales y tarjetas destacadas
     */
    interface AdcBlurPanel {
        /**
          * Intensidad del blur (sm, md, lg, xl)
          * @default "lg"
         */
        "blur"?: "sm" | "md" | "lg" | "xl";
        /**
          * Mostrar borde luminoso sutil
          * @default false
         */
        "glow"?: boolean;
        /**
          * Padding interno (none, sm, md, lg, xl)
          * @default "lg"
         */
        "padding"?: "none" | "sm" | "md" | "lg" | "xl";
        /**
          * Radio de borde (sm, md, lg, xl, full)
          * @default "xl"
         */
        "radius"?: "sm" | "md" | "lg" | "xl" | "full";
        /**
          * Variante de estilo - default: fondo semi-transparente estándar - elevated: más opaco con sombra pronunciada - subtle: casi transparente, solo blur
          * @default "default"
         */
        "variant"?: "default" | "elevated" | "subtle";
    }
    interface AdcButton {
        "ariaLabel"?: string;
        "disabled"?: boolean;
        "href"?: string;
        /**
          * Label text - when provided, takes precedence over slot content for dynamic updates
         */
        "label"?: string;
        "onAdcClick"?: (event: AdcButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * @default "primary"
         */
        "variant"?: "primary" | "accent";
    }
    interface AdcButtonRounded {
        "ariaLabel"?: string;
        "href"?: string;
        "onAdcClick"?: (event: AdcButtonRoundedCustomEvent<MouseEvent>) => void;
        /**
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * Visual variant
          * @default "default"
         */
        "variant"?: "default" | "danger";
    }
    interface AdcCallout {
        /**
          * @default "note"
         */
        "role"?: "note" | "status" | "alert";
        /**
          * @default "info"
         */
        "tone"?: "info" | "warning" | "success" | "error";
    }
    interface AdcCodeBlock {
        "ariaLabel"?: string;
        /**
          * @default ""
         */
        "content"?: string;
        "language"?: string;
    }
    interface AdcContentCard {
        "bannerAlt"?: string;
        "bannerUrl"?: string;
        /**
          * @default false
         */
        "compact"?: boolean;
        "description"?: string;
        "href"?: string;
        "onCardClick"?: (event: AdcContentCardCustomEvent<MouseEvent>) => void;
        /**
          * @default ""
         */
        "title"?: string;
    }
    interface AdcCustomError {
        /**
          * Auto-dismiss timeout in ms (only for toast variant). 0 = no auto-dismiss
          * @default 5000
         */
        "dismissTimeout"?: number;
        /**
          * If true, catches all errors not handled by specific key handlers
          * @default false
         */
        "global"?: boolean;
        /**
          * If true, listens for unhandled promise rejections
          * @default false
         */
        "handleUnhandled"?: boolean;
        /**
          * JSON array of error keys to handle. If empty and not global, shows warning.
         */
        "keys"?: string;
        /**
          * Maximum number of stacked toasts
          * @default 5
         */
        "maxStack"?: number;
        /**
          * Display variant: callout (inline) or toast (floating notification)
          * @default "toast"
         */
        "variant"?: "callout" | "toast";
    }
    interface AdcDivider {
    }
    interface AdcDropdownMenu {
        /**
          * @default "left"
         */
        "alignState"?: "left" | "right";
        /**
          * @default []
         */
        "items"?: DropdownMenuItem[];
        "onAdcItemClick"?: (event: AdcDropdownMenuCustomEvent<DropdownMenuItem>) => void;
        /**
          * @default true
         */
        "openOnHover"?: boolean;
    }
    interface AdcFeatureCard {
        /**
          * @default true
         */
        "staticRender"?: boolean;
        /**
          * @default ""
         */
        "title"?: string;
    }
    interface AdcIconAppCommunity {
        /**
          * @default "1.75rem"
         */
        "size"?: string;
    }
    interface AdcIconAppIdentity {
        /**
          * @default "1.75rem"
         */
        "size"?: string;
    }
    interface AdcIconCommunity {
        /**
          * @default "2rem"
         */
        "size"?: string;
    }
    interface AdcIconLearning {
        /**
          * @default "2rem"
         */
        "size"?: string;
    }
    interface AdcIconLeftArrow {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcIconLogout {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcIconNitro {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcIconOpensource {
        /**
          * @default "2rem"
         */
        "size"?: string;
    }
    interface AdcIconPencil {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcIconVip {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcInlineTokens {
        /**
          * @default ""
         */
        "fallback"?: string;
        /**
          * @default []
         */
        "tokens"?: InlineToken[];
    }
    interface AdcInput {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "inputId"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default "text"
         */
        "type"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface AdcLayout {
        "apiBaseUrl"?: string;
        "authUrl"?: string;
        /**
          * @default "Abby's Digital Cafe"
         */
        "brandName"?: string;
        /**
          * @default "Una taza de código con tintes de amistad"
         */
        "brandSlogan"?: string;
        /**
          * @default "https://abbytec.dev.ar/"
         */
        "creatorHref"?: string;
        /**
          * @default "Abbytec"
         */
        "creatorName"?: string;
        /**
          * @default "/"
         */
        "homeHref"?: string;
        /**
          * @default "ADC"
         */
        "logoAlt"?: string;
        /**
          * @default "/ui/images/mini-logo.webp"
         */
        "logoSrc"?: string;
        /**
          * @default true
         */
        "showAccessButton"?: boolean;
    }
    interface AdcListBlock {
        "ariaLabel"?: string;
        /**
          * @default []
         */
        "items"?: string[];
        /**
          * @default false
         */
        "ordered"?: boolean;
        "start"?: number;
    }
    interface AdcLpBadge {
        "as"?: "button" | "span";
        /**
          * @default ""
         */
        "color"?: string;
        "onAdcClick"?: (event: AdcLpBadgeCustomEvent<void>) => void;
        "slug"?: string;
        /**
          * @default ""
         */
        "title"?: string;
    }
    interface AdcModal {
        /**
          * Whether clicking the backdrop closes the modal
          * @default true
         */
        "dismissOnBackdrop"?: boolean;
        /**
          * Whether pressing Escape closes the modal
          * @default true
         */
        "dismissOnEscape"?: boolean;
        /**
          * Modal title
          * @default ""
         */
        "modalTitle"?: string;
        "onAdcClose"?: (event: AdcModalCustomEvent<void>) => void;
        /**
          * Whether the modal is visible
          * @default false
         */
        "open"?: boolean;
        /**
          * Size variant
          * @default "md"
         */
        "size"?: "sm" | "md" | "lg";
    }
    interface AdcPagination {
        /**
          * Current page (1-indexed)
          * @default 1
         */
        "currentPage"?: number;
        /**
          * Max visible page buttons
          * @default 5
         */
        "maxVisible"?: number;
        "onAdcPageChange"?: (event: AdcPaginationCustomEvent<number>) => void;
        /**
          * Total number of pages
          * @default 1
         */
        "totalPages"?: number;
    }
    interface AdcQuote {
        /**
          * @default true
         */
        "staticRender"?: boolean;
    }
    interface AdcSearchInput {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * @default 300
         */
        "debounce"?: number;
        /**
          * @default ""
         */
        "inputId"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        "onAdcInput"?: (event: AdcSearchInputCustomEvent<string>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default "text"
         */
        "type"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface AdcSelect {
        "onAdcChange"?: (event: AdcSelectCustomEvent<string>) => void;
        /**
          * @default []
         */
        "options"?: SelectOption[];
        /**
          * @default "Seleccione"
         */
        "placeholder"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface AdcShareButtons {
        /**
          * @default ""
         */
        "description"?: string;
        /**
          * @default ""
         */
        "title"?: string;
        /**
          * @default ""
         */
        "url"?: string;
    }
    interface AdcSiteFooter {
        /**
          * @default ""
         */
        "brandName"?: string;
        /**
          * @default ""
         */
        "brandSlogan"?: string;
        /**
          * @default ""
         */
        "creatorHref"?: string;
        /**
          * @default ""
         */
        "creatorName"?: string;
        /**
          * @default false
         */
        "lowerSign"?: boolean;
        /**
          * @default false
         */
        "registered"?: boolean;
    }
    interface AdcSiteHeader {
        /**
          * URL base de la API (en dev: http://localhost:3000, en prod: vacío)
          * @default ["localhost", "127.0.0.1"].includes(globalThis.location?.hostname) 		? `${globalThis.location?.protocol}//${globalThis.location?.hostname}:3000` 		: ""
         */
        "apiBaseUrl"?: string;
        /**
          * URL base para auth (dev vs prod)
          * @default `${globalThis.location?.protocol}//auth.adigitalcafe.com${globalThis.location?.port ? `:${globalThis.location?.port}` : ""}`
         */
        "authUrl"?: string;
        /**
          * @default "/"
         */
        "homeHref"?: string;
        /**
          * @default ""
         */
        "logoAlt"?: string;
        /**
          * @default ""
         */
        "logoSrc"?: string;
        /**
          * Mostrar botón de acceso/perfil
          * @default true
         */
        "showAccessButton"?: boolean;
        /**
          * Items del menú de usuario (array de {label, href, icon?})
          * @default []
         */
        "userMenuItems"?: AccessMenuItem1[];
    }
    /**
     * Skeleton loader component for placeholder content while loading
     * @example <adc-skeleton variant="text" />
     * <adc-skeleton variant="circular" width="48px" height="48px" />
     * <adc-skeleton variant="rectangular" height="200px" />
     * <adc-skeleton variant="button" />
     * <adc-skeleton variant="input" />
     */
    interface AdcSkeleton {
        /**
          * Animation type
          * @default "pulse"
         */
        "animation"?: "pulse" | "wave" | "none";
        /**
          * Custom height (CSS value). Defaults vary by variant
         */
        "height"?: string;
        /**
          * Number of lines for text variant
          * @default 1
         */
        "lines"?: number;
        /**
          * Border radius override
         */
        "rounded"?: string;
        /**
          * Variant determines the shape of the skeleton
          * @default "text"
         */
        "variant"?: "text" | "circular" | "rectangular" | "button" | "input";
        /**
          * Custom width (CSS value). Defaults vary by variant
         */
        "width"?: string;
    }
    interface AdcStarRating {
        "average"?: number | null;
        /**
          * @default false
         */
        "canRate"?: boolean;
        "count"?: number | null;
        "myRating"?: number | null;
        "onAdcRate"?: (event: AdcStarRatingCustomEvent<number>) => void;
        /**
          * @default false
         */
        "pending"?: boolean;
    }
    interface AdcTableBlock {
        "caption"?: string;
        "columnAlign"?: Array<"left" | "center" | "right">;
        /**
          * @default []
         */
        "header"?: string[];
        /**
          * @default false
         */
        "rowHeaders"?: boolean;
        /**
          * @default []
         */
        "rows"?: string[][];
    }
    interface AdcTabs {
        /**
          * Currently active tab ID
          * @default ""
         */
        "activeTab"?: string;
        "onAdcTabChange"?: (event: AdcTabsCustomEvent<string>) => void;
        /**
          * Tab items to display
          * @default []
         */
        "tabs"?: TabItem[] | string;
        /**
          * Visual variant
          * @default "underline"
         */
        "variant"?: "underline" | "pills";
    }
    interface AdcTestimonialCard {
        /**
          * @default ""
         */
        "author"?: string;
        /**
          * @default true
         */
        "staticRender"?: boolean;
    }
    interface AdcText {
        /**
          * @default true
         */
        "contain"?: boolean;
        /**
          * @default true
         */
        "staticRender"?: boolean;
    }
    interface AdcToggle {
        /**
          * Accessible name
         */
        "ariaLabel"?: string;
        /**
          * Whether the toggle is checked
          * @default false
         */
        "checked"?: boolean;
        /**
          * Whether the toggle is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Label text
         */
        "label"?: string;
        "onAdcChange"?: (event: AdcToggleCustomEvent<boolean>) => void;
    }
    interface AdcToggleBadge {
        /**
          * Whether the badge is in the active/selected state
          * @default false
         */
        "active"?: boolean;
        /**
          * Emitted when tapped
         */
        "onAdcToggle"?: (event: AdcToggleBadgeCustomEvent<void>) => void;
    }
    /**
     * Componente YouTube Facade para carga perezosa de videos
     * Muestra una thumbnail clickeable en lugar de cargar el iframe inmediatamente
     * Mejora performance al evitar cargar el player de YouTube hasta que sea necesario
     */
    interface AdcYoutubeFacade {
        /**
          * Alto del contenedor (opcional, por defecto responsive 16:9)
         */
        "height"?: string;
        /**
          * URL o ID del video de YouTube (acepta URL completa o solo el ID)
         */
        "src": string;
        /**
          * Título del video para accesibilidad
          * @default "Video de YouTube"
         */
        "title"?: string;
        /**
          * Ancho del contenedor (opcional, por defecto responsive)
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "adc-access-button": AdcAccessButton;
        "adc-apps-menu": AdcAppsMenu;
        "adc-badge": AdcBadge;
        "adc-blocks-renderer": AdcBlocksRenderer;
        "adc-blur-panel": AdcBlurPanel;
        "adc-button": AdcButton;
        "adc-button-rounded": AdcButtonRounded;
        "adc-callout": AdcCallout;
        "adc-code-block": AdcCodeBlock;
        "adc-content-card": AdcContentCard;
        "adc-custom-error": AdcCustomError;
        "adc-divider": AdcDivider;
        "adc-dropdown-menu": AdcDropdownMenu;
        "adc-feature-card": AdcFeatureCard;
        "adc-icon-app-community": AdcIconAppCommunity;
        "adc-icon-app-identity": AdcIconAppIdentity;
        "adc-icon-community": AdcIconCommunity;
        "adc-icon-learning": AdcIconLearning;
        "adc-icon-left-arrow": AdcIconLeftArrow;
        "adc-icon-logout": AdcIconLogout;
        "adc-icon-nitro": AdcIconNitro;
        "adc-icon-opensource": AdcIconOpensource;
        "adc-icon-pencil": AdcIconPencil;
        "adc-icon-vip": AdcIconVip;
        "adc-inline-tokens": AdcInlineTokens;
        "adc-input": AdcInput;
        "adc-layout": AdcLayout;
        "adc-list-block": AdcListBlock;
        "adc-lp-badge": AdcLpBadge;
        "adc-modal": AdcModal;
        "adc-pagination": AdcPagination;
        "adc-quote": AdcQuote;
        "adc-search-input": AdcSearchInput;
        "adc-select": AdcSelect;
        "adc-share-buttons": AdcShareButtons;
        "adc-site-footer": AdcSiteFooter;
        "adc-site-header": AdcSiteHeader;
        "adc-skeleton": AdcSkeleton;
        "adc-star-rating": AdcStarRating;
        "adc-table-block": AdcTableBlock;
        "adc-tabs": AdcTabs;
        "adc-testimonial-card": AdcTestimonialCard;
        "adc-text": AdcText;
        "adc-toggle": AdcToggle;
        "adc-toggle-badge": AdcToggleBadge;
        "adc-youtube-facade": AdcYoutubeFacade;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Botón de acceso que muestra:
             * - Si logueado: avatar + dropdown con menú de items + logout
             * - Si no logueado: botón "Ingresar" que redirige a auth
             */
            "adc-access-button": LocalJSX.AdcAccessButton & JSXBase.HTMLAttributes<HTMLAdcAccessButtonElement>;
            "adc-apps-menu": LocalJSX.AdcAppsMenu & JSXBase.HTMLAttributes<HTMLAdcAppsMenuElement>;
            "adc-badge": LocalJSX.AdcBadge & JSXBase.HTMLAttributes<HTMLAdcBadgeElement>;
            "adc-blocks-renderer": LocalJSX.AdcBlocksRenderer & JSXBase.HTMLAttributes<HTMLAdcBlocksRendererElement>;
            /**
             * Panel con efecto glassmorphism/blur
             * Ideal para formularios de auth, modales y tarjetas destacadas
             */
            "adc-blur-panel": LocalJSX.AdcBlurPanel & JSXBase.HTMLAttributes<HTMLAdcBlurPanelElement>;
            "adc-button": LocalJSX.AdcButton & JSXBase.HTMLAttributes<HTMLAdcButtonElement>;
            "adc-button-rounded": LocalJSX.AdcButtonRounded & JSXBase.HTMLAttributes<HTMLAdcButtonRoundedElement>;
            "adc-callout": LocalJSX.AdcCallout & JSXBase.HTMLAttributes<HTMLAdcCalloutElement>;
            "adc-code-block": LocalJSX.AdcCodeBlock & JSXBase.HTMLAttributes<HTMLAdcCodeBlockElement>;
            "adc-content-card": LocalJSX.AdcContentCard & JSXBase.HTMLAttributes<HTMLAdcContentCardElement>;
            "adc-custom-error": LocalJSX.AdcCustomError & JSXBase.HTMLAttributes<HTMLAdcCustomErrorElement>;
            "adc-divider": LocalJSX.AdcDivider & JSXBase.HTMLAttributes<HTMLAdcDividerElement>;
            "adc-dropdown-menu": LocalJSX.AdcDropdownMenu & JSXBase.HTMLAttributes<HTMLAdcDropdownMenuElement>;
            "adc-feature-card": LocalJSX.AdcFeatureCard & JSXBase.HTMLAttributes<HTMLAdcFeatureCardElement>;
            "adc-icon-app-community": LocalJSX.AdcIconAppCommunity & JSXBase.HTMLAttributes<HTMLAdcIconAppCommunityElement>;
            "adc-icon-app-identity": LocalJSX.AdcIconAppIdentity & JSXBase.HTMLAttributes<HTMLAdcIconAppIdentityElement>;
            "adc-icon-community": LocalJSX.AdcIconCommunity & JSXBase.HTMLAttributes<HTMLAdcIconCommunityElement>;
            "adc-icon-learning": LocalJSX.AdcIconLearning & JSXBase.HTMLAttributes<HTMLAdcIconLearningElement>;
            "adc-icon-left-arrow": LocalJSX.AdcIconLeftArrow & JSXBase.HTMLAttributes<HTMLAdcIconLeftArrowElement>;
            "adc-icon-logout": LocalJSX.AdcIconLogout & JSXBase.HTMLAttributes<HTMLAdcIconLogoutElement>;
            "adc-icon-nitro": LocalJSX.AdcIconNitro & JSXBase.HTMLAttributes<HTMLAdcIconNitroElement>;
            "adc-icon-opensource": LocalJSX.AdcIconOpensource & JSXBase.HTMLAttributes<HTMLAdcIconOpensourceElement>;
            "adc-icon-pencil": LocalJSX.AdcIconPencil & JSXBase.HTMLAttributes<HTMLAdcIconPencilElement>;
            "adc-icon-vip": LocalJSX.AdcIconVip & JSXBase.HTMLAttributes<HTMLAdcIconVipElement>;
            "adc-inline-tokens": LocalJSX.AdcInlineTokens & JSXBase.HTMLAttributes<HTMLAdcInlineTokensElement>;
            "adc-input": LocalJSX.AdcInput & JSXBase.HTMLAttributes<HTMLAdcInputElement>;
            "adc-layout": LocalJSX.AdcLayout & JSXBase.HTMLAttributes<HTMLAdcLayoutElement>;
            "adc-list-block": LocalJSX.AdcListBlock & JSXBase.HTMLAttributes<HTMLAdcListBlockElement>;
            "adc-lp-badge": LocalJSX.AdcLpBadge & JSXBase.HTMLAttributes<HTMLAdcLpBadgeElement>;
            "adc-modal": LocalJSX.AdcModal & JSXBase.HTMLAttributes<HTMLAdcModalElement>;
            "adc-pagination": LocalJSX.AdcPagination & JSXBase.HTMLAttributes<HTMLAdcPaginationElement>;
            "adc-quote": LocalJSX.AdcQuote & JSXBase.HTMLAttributes<HTMLAdcQuoteElement>;
            "adc-search-input": LocalJSX.AdcSearchInput & JSXBase.HTMLAttributes<HTMLAdcSearchInputElement>;
            "adc-select": LocalJSX.AdcSelect & JSXBase.HTMLAttributes<HTMLAdcSelectElement>;
            "adc-share-buttons": LocalJSX.AdcShareButtons & JSXBase.HTMLAttributes<HTMLAdcShareButtonsElement>;
            "adc-site-footer": LocalJSX.AdcSiteFooter & JSXBase.HTMLAttributes<HTMLAdcSiteFooterElement>;
            "adc-site-header": LocalJSX.AdcSiteHeader & JSXBase.HTMLAttributes<HTMLAdcSiteHeaderElement>;
            /**
             * Skeleton loader component for placeholder content while loading
             * @example <adc-skeleton variant="text" />
             * <adc-skeleton variant="circular" width="48px" height="48px" />
             * <adc-skeleton variant="rectangular" height="200px" />
             * <adc-skeleton variant="button" />
             * <adc-skeleton variant="input" />
             */
            "adc-skeleton": LocalJSX.AdcSkeleton & JSXBase.HTMLAttributes<HTMLAdcSkeletonElement>;
            "adc-star-rating": LocalJSX.AdcStarRating & JSXBase.HTMLAttributes<HTMLAdcStarRatingElement>;
            "adc-table-block": LocalJSX.AdcTableBlock & JSXBase.HTMLAttributes<HTMLAdcTableBlockElement>;
            "adc-tabs": LocalJSX.AdcTabs & JSXBase.HTMLAttributes<HTMLAdcTabsElement>;
            "adc-testimonial-card": LocalJSX.AdcTestimonialCard & JSXBase.HTMLAttributes<HTMLAdcTestimonialCardElement>;
            "adc-text": LocalJSX.AdcText & JSXBase.HTMLAttributes<HTMLAdcTextElement>;
            "adc-toggle": LocalJSX.AdcToggle & JSXBase.HTMLAttributes<HTMLAdcToggleElement>;
            "adc-toggle-badge": LocalJSX.AdcToggleBadge & JSXBase.HTMLAttributes<HTMLAdcToggleBadgeElement>;
            /**
             * Componente YouTube Facade para carga perezosa de videos
             * Muestra una thumbnail clickeable en lugar de cargar el iframe inmediatamente
             * Mejora performance al evitar cargar el player de YouTube hasta que sea necesario
             */
            "adc-youtube-facade": LocalJSX.AdcYoutubeFacade & JSXBase.HTMLAttributes<HTMLAdcYoutubeFacadeElement>;
        }
    }
}
