/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Block } from "./components/organisms/adc-blocks-renderer/adc-blocks-renderer";
import { DropdownMenuItem } from "./components/molecules/adc-dropdown-menu/adc-dropdown-menu";
import { InlineToken } from "./components/atoms/adc-inline-tokens/adc-inline-tokens";
import { SelectOption } from "./components/atoms/adc-select/adc-select";
export { Block } from "./components/organisms/adc-blocks-renderer/adc-blocks-renderer";
export { DropdownMenuItem } from "./components/molecules/adc-dropdown-menu/adc-dropdown-menu";
export { InlineToken } from "./components/atoms/adc-inline-tokens/adc-inline-tokens";
export { SelectOption } from "./components/atoms/adc-select/adc-select";
export namespace Components {
    interface AdcBlocksRenderer {
        /**
          * @default []
         */
        "blocks": Block[];
    }
    interface AdcButton {
        "ariaLabel"?: string;
        "href"?: string;
        /**
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
    }
    interface AdcButtonRounded {
        "ariaLabel"?: string;
        "href"?: string;
        /**
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
    }
    interface AdcCallout {
        /**
          * @default "note"
         */
        "role": "note" | "status" | "alert";
        /**
          * @default "info"
         */
        "tone": "info" | "warning" | "success" | "error";
    }
    interface AdcCodeBlock {
        "ariaLabel"?: string;
        /**
          * @default ""
         */
        "content": string;
        "language"?: string;
    }
    interface AdcContentCard {
        "bannerAlt"?: string;
        "bannerUrl"?: string;
        /**
          * @default false
         */
        "compact": boolean;
        "description"?: string;
        "href"?: string;
        /**
          * @default ""
         */
        "title": string;
    }
    interface AdcDivider {
    }
    interface AdcDropdownMenu {
        /**
          * @default "left"
         */
        "alignState": "left" | "right";
        /**
          * @default []
         */
        "items": DropdownMenuItem[];
        /**
          * @default true
         */
        "openOnHover": boolean;
    }
    interface AdcFeatureCard {
        /**
          * @default true
         */
        "staticRender": boolean;
        /**
          * @default ""
         */
        "title": string;
    }
    interface AdcIconCommunity {
        /**
          * @default "2rem"
         */
        "size": string;
    }
    interface AdcIconLearning {
        /**
          * @default "2rem"
         */
        "size": string;
    }
    interface AdcIconLeftArrow {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcIconLogout {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcIconNitro {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcIconOpensource {
        /**
          * @default "2rem"
         */
        "size": string;
    }
    interface AdcIconPencil {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcIconVip {
        /**
          * @default "1rem"
         */
        "size": string;
    }
    interface AdcInlineTokens {
        /**
          * @default ""
         */
        "fallback": string;
        /**
          * @default []
         */
        "tokens": InlineToken[];
    }
    interface AdcInput {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * @default ""
         */
        "inputId"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default "text"
         */
        "type"?: string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface AdcListBlock {
        "ariaLabel"?: string;
        /**
          * @default []
         */
        "items": string[];
        /**
          * @default false
         */
        "ordered": boolean;
        "start"?: number;
    }
    interface AdcLpBadge {
        "as"?: "button" | "span";
        /**
          * @default ""
         */
        "color": string;
        "slug"?: string;
        /**
          * @default ""
         */
        "title": string;
    }
    interface AdcQuote {
        /**
          * @default true
         */
        "staticRender": boolean;
    }
    interface AdcSearchInput {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * @default 300
         */
        "debounce": number;
        /**
          * @default ""
         */
        "inputId"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        /**
          * @default ""
         */
        "placeholder": string;
        /**
          * @default "text"
         */
        "type"?: string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface AdcSelect {
        /**
          * @default []
         */
        "options": SelectOption[];
        /**
          * @default "Seleccione"
         */
        "placeholder": string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface AdcShareButtons {
        /**
          * @default ""
         */
        "description": string;
        /**
          * @default ""
         */
        "title": string;
        /**
          * @default ""
         */
        "url": string;
    }
    interface AdcSiteFooter {
        /**
          * @default ""
         */
        "brandName": string;
        /**
          * @default ""
         */
        "brandSlogan": string;
        /**
          * @default ""
         */
        "creatorHref": string;
        /**
          * @default ""
         */
        "creatorName": string;
        /**
          * @default false
         */
        "lowerSign": boolean;
        /**
          * @default false
         */
        "registered": boolean;
    }
    interface AdcSiteHeader {
        /**
          * @default "/"
         */
        "homeHref": string;
        /**
          * @default ""
         */
        "logoAlt": string;
        /**
          * @default ""
         */
        "logoSrc": string;
    }
    interface AdcStarRating {
        "average"?: number | null;
        /**
          * @default false
         */
        "canRate": boolean;
        "count"?: number | null;
        "myRating"?: number | null;
        /**
          * @default false
         */
        "pending": boolean;
    }
    interface AdcTableBlock {
        "caption"?: string;
        "columnAlign"?: Array<"left" | "center" | "right">;
        /**
          * @default []
         */
        "header": string[];
        /**
          * @default false
         */
        "rowHeaders": boolean;
        /**
          * @default []
         */
        "rows": string[][];
    }
    interface AdcTestimonialCard {
        /**
          * @default ""
         */
        "author": string;
        /**
          * @default true
         */
        "staticRender": boolean;
    }
    interface AdcText {
        /**
          * @default true
         */
        "contain": boolean;
        /**
          * @default true
         */
        "staticRender": boolean;
    }
    /**
     * Componente YouTube Facade para carga perezosa de videos
     * Muestra una thumbnail clickeable en lugar de cargar el iframe inmediatamente
     * Mejora performance al evitar cargar el player de YouTube hasta que sea necesario
     */
    interface AdcYoutubeFacade {
        /**
          * Alto del contenedor (opcional, por defecto responsive 16:9)
         */
        "height"?: string;
        /**
          * Título del video para accesibilidad
          * @default "Video de YouTube"
         */
        "title": string;
        /**
          * ID del video de YouTube (extraído de la URL)
         */
        "videoId": string;
        /**
          * Ancho del contenedor (opcional, por defecto responsive)
         */
        "width"?: string;
    }
}
export interface AdcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcButtonElement;
}
export interface AdcButtonRoundedCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcButtonRoundedElement;
}
export interface AdcContentCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcContentCardElement;
}
export interface AdcDropdownMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcDropdownMenuElement;
}
export interface AdcInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcInputElement;
}
export interface AdcLpBadgeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcLpBadgeElement;
}
export interface AdcSearchInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcSearchInputElement;
}
export interface AdcSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcSelectElement;
}
export interface AdcStarRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAdcStarRatingElement;
}
declare global {
    interface HTMLAdcBlocksRendererElement extends Components.AdcBlocksRenderer, HTMLStencilElement {
    }
    var HTMLAdcBlocksRendererElement: {
        prototype: HTMLAdcBlocksRendererElement;
        new (): HTMLAdcBlocksRendererElement;
    };
    interface HTMLAdcButtonElementEventMap {
        "adcClick": MouseEvent;
    }
    interface HTMLAdcButtonElement extends Components.AdcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcButtonElementEventMap>(type: K, listener: (this: HTMLAdcButtonElement, ev: AdcButtonCustomEvent<HTMLAdcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcButtonElement: {
        prototype: HTMLAdcButtonElement;
        new (): HTMLAdcButtonElement;
    };
    interface HTMLAdcButtonRoundedElementEventMap {
        "adcClick": MouseEvent;
    }
    interface HTMLAdcButtonRoundedElement extends Components.AdcButtonRounded, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcButtonRoundedElementEventMap>(type: K, listener: (this: HTMLAdcButtonRoundedElement, ev: AdcButtonRoundedCustomEvent<HTMLAdcButtonRoundedElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcButtonRoundedElementEventMap>(type: K, listener: (this: HTMLAdcButtonRoundedElement, ev: AdcButtonRoundedCustomEvent<HTMLAdcButtonRoundedElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcButtonRoundedElement: {
        prototype: HTMLAdcButtonRoundedElement;
        new (): HTMLAdcButtonRoundedElement;
    };
    interface HTMLAdcCalloutElement extends Components.AdcCallout, HTMLStencilElement {
    }
    var HTMLAdcCalloutElement: {
        prototype: HTMLAdcCalloutElement;
        new (): HTMLAdcCalloutElement;
    };
    interface HTMLAdcCodeBlockElement extends Components.AdcCodeBlock, HTMLStencilElement {
    }
    var HTMLAdcCodeBlockElement: {
        prototype: HTMLAdcCodeBlockElement;
        new (): HTMLAdcCodeBlockElement;
    };
    interface HTMLAdcContentCardElementEventMap {
        "cardClick": MouseEvent;
    }
    interface HTMLAdcContentCardElement extends Components.AdcContentCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcContentCardElementEventMap>(type: K, listener: (this: HTMLAdcContentCardElement, ev: AdcContentCardCustomEvent<HTMLAdcContentCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcContentCardElementEventMap>(type: K, listener: (this: HTMLAdcContentCardElement, ev: AdcContentCardCustomEvent<HTMLAdcContentCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcContentCardElement: {
        prototype: HTMLAdcContentCardElement;
        new (): HTMLAdcContentCardElement;
    };
    interface HTMLAdcDividerElement extends Components.AdcDivider, HTMLStencilElement {
    }
    var HTMLAdcDividerElement: {
        prototype: HTMLAdcDividerElement;
        new (): HTMLAdcDividerElement;
    };
    interface HTMLAdcDropdownMenuElementEventMap {
        "adcItemClick": DropdownMenuItem;
    }
    interface HTMLAdcDropdownMenuElement extends Components.AdcDropdownMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcDropdownMenuElementEventMap>(type: K, listener: (this: HTMLAdcDropdownMenuElement, ev: AdcDropdownMenuCustomEvent<HTMLAdcDropdownMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcDropdownMenuElementEventMap>(type: K, listener: (this: HTMLAdcDropdownMenuElement, ev: AdcDropdownMenuCustomEvent<HTMLAdcDropdownMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcDropdownMenuElement: {
        prototype: HTMLAdcDropdownMenuElement;
        new (): HTMLAdcDropdownMenuElement;
    };
    interface HTMLAdcFeatureCardElement extends Components.AdcFeatureCard, HTMLStencilElement {
    }
    var HTMLAdcFeatureCardElement: {
        prototype: HTMLAdcFeatureCardElement;
        new (): HTMLAdcFeatureCardElement;
    };
    interface HTMLAdcIconCommunityElement extends Components.AdcIconCommunity, HTMLStencilElement {
    }
    var HTMLAdcIconCommunityElement: {
        prototype: HTMLAdcIconCommunityElement;
        new (): HTMLAdcIconCommunityElement;
    };
    interface HTMLAdcIconLearningElement extends Components.AdcIconLearning, HTMLStencilElement {
    }
    var HTMLAdcIconLearningElement: {
        prototype: HTMLAdcIconLearningElement;
        new (): HTMLAdcIconLearningElement;
    };
    interface HTMLAdcIconLeftArrowElement extends Components.AdcIconLeftArrow, HTMLStencilElement {
    }
    var HTMLAdcIconLeftArrowElement: {
        prototype: HTMLAdcIconLeftArrowElement;
        new (): HTMLAdcIconLeftArrowElement;
    };
    interface HTMLAdcIconLogoutElement extends Components.AdcIconLogout, HTMLStencilElement {
    }
    var HTMLAdcIconLogoutElement: {
        prototype: HTMLAdcIconLogoutElement;
        new (): HTMLAdcIconLogoutElement;
    };
    interface HTMLAdcIconNitroElement extends Components.AdcIconNitro, HTMLStencilElement {
    }
    var HTMLAdcIconNitroElement: {
        prototype: HTMLAdcIconNitroElement;
        new (): HTMLAdcIconNitroElement;
    };
    interface HTMLAdcIconOpensourceElement extends Components.AdcIconOpensource, HTMLStencilElement {
    }
    var HTMLAdcIconOpensourceElement: {
        prototype: HTMLAdcIconOpensourceElement;
        new (): HTMLAdcIconOpensourceElement;
    };
    interface HTMLAdcIconPencilElement extends Components.AdcIconPencil, HTMLStencilElement {
    }
    var HTMLAdcIconPencilElement: {
        prototype: HTMLAdcIconPencilElement;
        new (): HTMLAdcIconPencilElement;
    };
    interface HTMLAdcIconVipElement extends Components.AdcIconVip, HTMLStencilElement {
    }
    var HTMLAdcIconVipElement: {
        prototype: HTMLAdcIconVipElement;
        new (): HTMLAdcIconVipElement;
    };
    interface HTMLAdcInlineTokensElement extends Components.AdcInlineTokens, HTMLStencilElement {
    }
    var HTMLAdcInlineTokensElement: {
        prototype: HTMLAdcInlineTokensElement;
        new (): HTMLAdcInlineTokensElement;
    };
    interface HTMLAdcInputElementEventMap {
        "adcInput": string;
    }
    interface HTMLAdcInputElement extends Components.AdcInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcInputElementEventMap>(type: K, listener: (this: HTMLAdcInputElement, ev: AdcInputCustomEvent<HTMLAdcInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcInputElementEventMap>(type: K, listener: (this: HTMLAdcInputElement, ev: AdcInputCustomEvent<HTMLAdcInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcInputElement: {
        prototype: HTMLAdcInputElement;
        new (): HTMLAdcInputElement;
    };
    interface HTMLAdcListBlockElement extends Components.AdcListBlock, HTMLStencilElement {
    }
    var HTMLAdcListBlockElement: {
        prototype: HTMLAdcListBlockElement;
        new (): HTMLAdcListBlockElement;
    };
    interface HTMLAdcLpBadgeElementEventMap {
        "adcClick": void;
    }
    interface HTMLAdcLpBadgeElement extends Components.AdcLpBadge, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcLpBadgeElementEventMap>(type: K, listener: (this: HTMLAdcLpBadgeElement, ev: AdcLpBadgeCustomEvent<HTMLAdcLpBadgeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcLpBadgeElementEventMap>(type: K, listener: (this: HTMLAdcLpBadgeElement, ev: AdcLpBadgeCustomEvent<HTMLAdcLpBadgeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcLpBadgeElement: {
        prototype: HTMLAdcLpBadgeElement;
        new (): HTMLAdcLpBadgeElement;
    };
    interface HTMLAdcQuoteElement extends Components.AdcQuote, HTMLStencilElement {
    }
    var HTMLAdcQuoteElement: {
        prototype: HTMLAdcQuoteElement;
        new (): HTMLAdcQuoteElement;
    };
    interface HTMLAdcSearchInputElementEventMap {
        "adcInput": string;
    }
    interface HTMLAdcSearchInputElement extends Components.AdcSearchInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcSearchInputElementEventMap>(type: K, listener: (this: HTMLAdcSearchInputElement, ev: AdcSearchInputCustomEvent<HTMLAdcSearchInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcSearchInputElementEventMap>(type: K, listener: (this: HTMLAdcSearchInputElement, ev: AdcSearchInputCustomEvent<HTMLAdcSearchInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcSearchInputElement: {
        prototype: HTMLAdcSearchInputElement;
        new (): HTMLAdcSearchInputElement;
    };
    interface HTMLAdcSelectElementEventMap {
        "adcChange": string;
    }
    interface HTMLAdcSelectElement extends Components.AdcSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcSelectElementEventMap>(type: K, listener: (this: HTMLAdcSelectElement, ev: AdcSelectCustomEvent<HTMLAdcSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcSelectElementEventMap>(type: K, listener: (this: HTMLAdcSelectElement, ev: AdcSelectCustomEvent<HTMLAdcSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcSelectElement: {
        prototype: HTMLAdcSelectElement;
        new (): HTMLAdcSelectElement;
    };
    interface HTMLAdcShareButtonsElement extends Components.AdcShareButtons, HTMLStencilElement {
    }
    var HTMLAdcShareButtonsElement: {
        prototype: HTMLAdcShareButtonsElement;
        new (): HTMLAdcShareButtonsElement;
    };
    interface HTMLAdcSiteFooterElement extends Components.AdcSiteFooter, HTMLStencilElement {
    }
    var HTMLAdcSiteFooterElement: {
        prototype: HTMLAdcSiteFooterElement;
        new (): HTMLAdcSiteFooterElement;
    };
    interface HTMLAdcSiteHeaderElement extends Components.AdcSiteHeader, HTMLStencilElement {
    }
    var HTMLAdcSiteHeaderElement: {
        prototype: HTMLAdcSiteHeaderElement;
        new (): HTMLAdcSiteHeaderElement;
    };
    interface HTMLAdcStarRatingElementEventMap {
        "adcRate": number;
    }
    interface HTMLAdcStarRatingElement extends Components.AdcStarRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAdcStarRatingElementEventMap>(type: K, listener: (this: HTMLAdcStarRatingElement, ev: AdcStarRatingCustomEvent<HTMLAdcStarRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAdcStarRatingElementEventMap>(type: K, listener: (this: HTMLAdcStarRatingElement, ev: AdcStarRatingCustomEvent<HTMLAdcStarRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAdcStarRatingElement: {
        prototype: HTMLAdcStarRatingElement;
        new (): HTMLAdcStarRatingElement;
    };
    interface HTMLAdcTableBlockElement extends Components.AdcTableBlock, HTMLStencilElement {
    }
    var HTMLAdcTableBlockElement: {
        prototype: HTMLAdcTableBlockElement;
        new (): HTMLAdcTableBlockElement;
    };
    interface HTMLAdcTestimonialCardElement extends Components.AdcTestimonialCard, HTMLStencilElement {
    }
    var HTMLAdcTestimonialCardElement: {
        prototype: HTMLAdcTestimonialCardElement;
        new (): HTMLAdcTestimonialCardElement;
    };
    interface HTMLAdcTextElement extends Components.AdcText, HTMLStencilElement {
    }
    var HTMLAdcTextElement: {
        prototype: HTMLAdcTextElement;
        new (): HTMLAdcTextElement;
    };
    /**
     * Componente YouTube Facade para carga perezosa de videos
     * Muestra una thumbnail clickeable en lugar de cargar el iframe inmediatamente
     * Mejora performance al evitar cargar el player de YouTube hasta que sea necesario
     */
    interface HTMLAdcYoutubeFacadeElement extends Components.AdcYoutubeFacade, HTMLStencilElement {
    }
    var HTMLAdcYoutubeFacadeElement: {
        prototype: HTMLAdcYoutubeFacadeElement;
        new (): HTMLAdcYoutubeFacadeElement;
    };
    interface HTMLElementTagNameMap {
        "adc-blocks-renderer": HTMLAdcBlocksRendererElement;
        "adc-button": HTMLAdcButtonElement;
        "adc-button-rounded": HTMLAdcButtonRoundedElement;
        "adc-callout": HTMLAdcCalloutElement;
        "adc-code-block": HTMLAdcCodeBlockElement;
        "adc-content-card": HTMLAdcContentCardElement;
        "adc-divider": HTMLAdcDividerElement;
        "adc-dropdown-menu": HTMLAdcDropdownMenuElement;
        "adc-feature-card": HTMLAdcFeatureCardElement;
        "adc-icon-community": HTMLAdcIconCommunityElement;
        "adc-icon-learning": HTMLAdcIconLearningElement;
        "adc-icon-left-arrow": HTMLAdcIconLeftArrowElement;
        "adc-icon-logout": HTMLAdcIconLogoutElement;
        "adc-icon-nitro": HTMLAdcIconNitroElement;
        "adc-icon-opensource": HTMLAdcIconOpensourceElement;
        "adc-icon-pencil": HTMLAdcIconPencilElement;
        "adc-icon-vip": HTMLAdcIconVipElement;
        "adc-inline-tokens": HTMLAdcInlineTokensElement;
        "adc-input": HTMLAdcInputElement;
        "adc-list-block": HTMLAdcListBlockElement;
        "adc-lp-badge": HTMLAdcLpBadgeElement;
        "adc-quote": HTMLAdcQuoteElement;
        "adc-search-input": HTMLAdcSearchInputElement;
        "adc-select": HTMLAdcSelectElement;
        "adc-share-buttons": HTMLAdcShareButtonsElement;
        "adc-site-footer": HTMLAdcSiteFooterElement;
        "adc-site-header": HTMLAdcSiteHeaderElement;
        "adc-star-rating": HTMLAdcStarRatingElement;
        "adc-table-block": HTMLAdcTableBlockElement;
        "adc-testimonial-card": HTMLAdcTestimonialCardElement;
        "adc-text": HTMLAdcTextElement;
        "adc-youtube-facade": HTMLAdcYoutubeFacadeElement;
    }
}
declare namespace LocalJSX {
    interface AdcBlocksRenderer {
        /**
          * @default []
         */
        "blocks"?: Block[];
    }
    interface AdcButton {
        "ariaLabel"?: string;
        "href"?: string;
        "onAdcClick"?: (event: AdcButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
    }
    interface AdcButtonRounded {
        "ariaLabel"?: string;
        "href"?: string;
        "onAdcClick"?: (event: AdcButtonRoundedCustomEvent<MouseEvent>) => void;
        /**
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
    }
    interface AdcCallout {
        /**
          * @default "note"
         */
        "role"?: "note" | "status" | "alert";
        /**
          * @default "info"
         */
        "tone"?: "info" | "warning" | "success" | "error";
    }
    interface AdcCodeBlock {
        "ariaLabel"?: string;
        /**
          * @default ""
         */
        "content"?: string;
        "language"?: string;
    }
    interface AdcContentCard {
        "bannerAlt"?: string;
        "bannerUrl"?: string;
        /**
          * @default false
         */
        "compact"?: boolean;
        "description"?: string;
        "href"?: string;
        "onCardClick"?: (event: AdcContentCardCustomEvent<MouseEvent>) => void;
        /**
          * @default ""
         */
        "title"?: string;
    }
    interface AdcDivider {
    }
    interface AdcDropdownMenu {
        /**
          * @default "left"
         */
        "alignState"?: "left" | "right";
        /**
          * @default []
         */
        "items"?: DropdownMenuItem[];
        "onAdcItemClick"?: (event: AdcDropdownMenuCustomEvent<DropdownMenuItem>) => void;
        /**
          * @default true
         */
        "openOnHover"?: boolean;
    }
    interface AdcFeatureCard {
        /**
          * @default true
         */
        "staticRender"?: boolean;
        /**
          * @default ""
         */
        "title"?: string;
    }
    interface AdcIconCommunity {
        /**
          * @default "2rem"
         */
        "size"?: string;
    }
    interface AdcIconLearning {
        /**
          * @default "2rem"
         */
        "size"?: string;
    }
    interface AdcIconLeftArrow {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcIconLogout {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcIconNitro {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcIconOpensource {
        /**
          * @default "2rem"
         */
        "size"?: string;
    }
    interface AdcIconPencil {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcIconVip {
        /**
          * @default "1rem"
         */
        "size"?: string;
    }
    interface AdcInlineTokens {
        /**
          * @default ""
         */
        "fallback"?: string;
        /**
          * @default []
         */
        "tokens"?: InlineToken[];
    }
    interface AdcInput {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * @default ""
         */
        "inputId"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        "onAdcInput"?: (event: AdcInputCustomEvent<string>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default "text"
         */
        "type"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface AdcListBlock {
        "ariaLabel"?: string;
        /**
          * @default []
         */
        "items"?: string[];
        /**
          * @default false
         */
        "ordered"?: boolean;
        "start"?: number;
    }
    interface AdcLpBadge {
        "as"?: "button" | "span";
        /**
          * @default ""
         */
        "color"?: string;
        "onAdcClick"?: (event: AdcLpBadgeCustomEvent<void>) => void;
        "slug"?: string;
        /**
          * @default ""
         */
        "title"?: string;
    }
    interface AdcQuote {
        /**
          * @default true
         */
        "staticRender"?: boolean;
    }
    interface AdcSearchInput {
        /**
          * @default ""
         */
        "ariaLabel"?: string;
        /**
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * @default 300
         */
        "debounce"?: number;
        /**
          * @default ""
         */
        "inputId"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        "onAdcInput"?: (event: AdcSearchInputCustomEvent<string>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default "text"
         */
        "type"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface AdcSelect {
        "onAdcChange"?: (event: AdcSelectCustomEvent<string>) => void;
        /**
          * @default []
         */
        "options"?: SelectOption[];
        /**
          * @default "Seleccione"
         */
        "placeholder"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface AdcShareButtons {
        /**
          * @default ""
         */
        "description"?: string;
        /**
          * @default ""
         */
        "title"?: string;
        /**
          * @default ""
         */
        "url"?: string;
    }
    interface AdcSiteFooter {
        /**
          * @default ""
         */
        "brandName"?: string;
        /**
          * @default ""
         */
        "brandSlogan"?: string;
        /**
          * @default ""
         */
        "creatorHref"?: string;
        /**
          * @default ""
         */
        "creatorName"?: string;
        /**
          * @default false
         */
        "lowerSign"?: boolean;
        /**
          * @default false
         */
        "registered"?: boolean;
    }
    interface AdcSiteHeader {
        /**
          * @default "/"
         */
        "homeHref"?: string;
        /**
          * @default ""
         */
        "logoAlt"?: string;
        /**
          * @default ""
         */
        "logoSrc"?: string;
    }
    interface AdcStarRating {
        "average"?: number | null;
        /**
          * @default false
         */
        "canRate"?: boolean;
        "count"?: number | null;
        "myRating"?: number | null;
        "onAdcRate"?: (event: AdcStarRatingCustomEvent<number>) => void;
        /**
          * @default false
         */
        "pending"?: boolean;
    }
    interface AdcTableBlock {
        "caption"?: string;
        "columnAlign"?: Array<"left" | "center" | "right">;
        /**
          * @default []
         */
        "header"?: string[];
        /**
          * @default false
         */
        "rowHeaders"?: boolean;
        /**
          * @default []
         */
        "rows"?: string[][];
    }
    interface AdcTestimonialCard {
        /**
          * @default ""
         */
        "author"?: string;
        /**
          * @default true
         */
        "staticRender"?: boolean;
    }
    interface AdcText {
        /**
          * @default true
         */
        "contain"?: boolean;
        /**
          * @default true
         */
        "staticRender"?: boolean;
    }
    /**
     * Componente YouTube Facade para carga perezosa de videos
     * Muestra una thumbnail clickeable en lugar de cargar el iframe inmediatamente
     * Mejora performance al evitar cargar el player de YouTube hasta que sea necesario
     */
    interface AdcYoutubeFacade {
        /**
          * Alto del contenedor (opcional, por defecto responsive 16:9)
         */
        "height"?: string;
        /**
          * Título del video para accesibilidad
          * @default "Video de YouTube"
         */
        "title"?: string;
        /**
          * ID del video de YouTube (extraído de la URL)
         */
        "videoId": string;
        /**
          * Ancho del contenedor (opcional, por defecto responsive)
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "adc-blocks-renderer": AdcBlocksRenderer;
        "adc-button": AdcButton;
        "adc-button-rounded": AdcButtonRounded;
        "adc-callout": AdcCallout;
        "adc-code-block": AdcCodeBlock;
        "adc-content-card": AdcContentCard;
        "adc-divider": AdcDivider;
        "adc-dropdown-menu": AdcDropdownMenu;
        "adc-feature-card": AdcFeatureCard;
        "adc-icon-community": AdcIconCommunity;
        "adc-icon-learning": AdcIconLearning;
        "adc-icon-left-arrow": AdcIconLeftArrow;
        "adc-icon-logout": AdcIconLogout;
        "adc-icon-nitro": AdcIconNitro;
        "adc-icon-opensource": AdcIconOpensource;
        "adc-icon-pencil": AdcIconPencil;
        "adc-icon-vip": AdcIconVip;
        "adc-inline-tokens": AdcInlineTokens;
        "adc-input": AdcInput;
        "adc-list-block": AdcListBlock;
        "adc-lp-badge": AdcLpBadge;
        "adc-quote": AdcQuote;
        "adc-search-input": AdcSearchInput;
        "adc-select": AdcSelect;
        "adc-share-buttons": AdcShareButtons;
        "adc-site-footer": AdcSiteFooter;
        "adc-site-header": AdcSiteHeader;
        "adc-star-rating": AdcStarRating;
        "adc-table-block": AdcTableBlock;
        "adc-testimonial-card": AdcTestimonialCard;
        "adc-text": AdcText;
        "adc-youtube-facade": AdcYoutubeFacade;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "adc-blocks-renderer": LocalJSX.AdcBlocksRenderer & JSXBase.HTMLAttributes<HTMLAdcBlocksRendererElement>;
            "adc-button": LocalJSX.AdcButton & JSXBase.HTMLAttributes<HTMLAdcButtonElement>;
            "adc-button-rounded": LocalJSX.AdcButtonRounded & JSXBase.HTMLAttributes<HTMLAdcButtonRoundedElement>;
            "adc-callout": LocalJSX.AdcCallout & JSXBase.HTMLAttributes<HTMLAdcCalloutElement>;
            "adc-code-block": LocalJSX.AdcCodeBlock & JSXBase.HTMLAttributes<HTMLAdcCodeBlockElement>;
            "adc-content-card": LocalJSX.AdcContentCard & JSXBase.HTMLAttributes<HTMLAdcContentCardElement>;
            "adc-divider": LocalJSX.AdcDivider & JSXBase.HTMLAttributes<HTMLAdcDividerElement>;
            "adc-dropdown-menu": LocalJSX.AdcDropdownMenu & JSXBase.HTMLAttributes<HTMLAdcDropdownMenuElement>;
            "adc-feature-card": LocalJSX.AdcFeatureCard & JSXBase.HTMLAttributes<HTMLAdcFeatureCardElement>;
            "adc-icon-community": LocalJSX.AdcIconCommunity & JSXBase.HTMLAttributes<HTMLAdcIconCommunityElement>;
            "adc-icon-learning": LocalJSX.AdcIconLearning & JSXBase.HTMLAttributes<HTMLAdcIconLearningElement>;
            "adc-icon-left-arrow": LocalJSX.AdcIconLeftArrow & JSXBase.HTMLAttributes<HTMLAdcIconLeftArrowElement>;
            "adc-icon-logout": LocalJSX.AdcIconLogout & JSXBase.HTMLAttributes<HTMLAdcIconLogoutElement>;
            "adc-icon-nitro": LocalJSX.AdcIconNitro & JSXBase.HTMLAttributes<HTMLAdcIconNitroElement>;
            "adc-icon-opensource": LocalJSX.AdcIconOpensource & JSXBase.HTMLAttributes<HTMLAdcIconOpensourceElement>;
            "adc-icon-pencil": LocalJSX.AdcIconPencil & JSXBase.HTMLAttributes<HTMLAdcIconPencilElement>;
            "adc-icon-vip": LocalJSX.AdcIconVip & JSXBase.HTMLAttributes<HTMLAdcIconVipElement>;
            "adc-inline-tokens": LocalJSX.AdcInlineTokens & JSXBase.HTMLAttributes<HTMLAdcInlineTokensElement>;
            "adc-input": LocalJSX.AdcInput & JSXBase.HTMLAttributes<HTMLAdcInputElement>;
            "adc-list-block": LocalJSX.AdcListBlock & JSXBase.HTMLAttributes<HTMLAdcListBlockElement>;
            "adc-lp-badge": LocalJSX.AdcLpBadge & JSXBase.HTMLAttributes<HTMLAdcLpBadgeElement>;
            "adc-quote": LocalJSX.AdcQuote & JSXBase.HTMLAttributes<HTMLAdcQuoteElement>;
            "adc-search-input": LocalJSX.AdcSearchInput & JSXBase.HTMLAttributes<HTMLAdcSearchInputElement>;
            "adc-select": LocalJSX.AdcSelect & JSXBase.HTMLAttributes<HTMLAdcSelectElement>;
            "adc-share-buttons": LocalJSX.AdcShareButtons & JSXBase.HTMLAttributes<HTMLAdcShareButtonsElement>;
            "adc-site-footer": LocalJSX.AdcSiteFooter & JSXBase.HTMLAttributes<HTMLAdcSiteFooterElement>;
            "adc-site-header": LocalJSX.AdcSiteHeader & JSXBase.HTMLAttributes<HTMLAdcSiteHeaderElement>;
            "adc-star-rating": LocalJSX.AdcStarRating & JSXBase.HTMLAttributes<HTMLAdcStarRatingElement>;
            "adc-table-block": LocalJSX.AdcTableBlock & JSXBase.HTMLAttributes<HTMLAdcTableBlockElement>;
            "adc-testimonial-card": LocalJSX.AdcTestimonialCard & JSXBase.HTMLAttributes<HTMLAdcTestimonialCardElement>;
            "adc-text": LocalJSX.AdcText & JSXBase.HTMLAttributes<HTMLAdcTextElement>;
            /**
             * Componente YouTube Facade para carga perezosa de videos
             * Muestra una thumbnail clickeable en lugar de cargar el iframe inmediatamente
             * Mejora performance al evitar cargar el player de YouTube hasta que sea necesario
             */
            "adc-youtube-facade": LocalJSX.AdcYoutubeFacade & JSXBase.HTMLAttributes<HTMLAdcYoutubeFacadeElement>;
        }
    }
}
